/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.technobsoftwares.gpiec.formulario;

import br.com.technobsoftwares.gpiec.dao.LocalDAO;
import br.com.technobsoftwares.gpiec.dao.Tipo_PatrimonioDAO;
import br.com.technobsoftwares.gpiec.modelo.Local;
import br.com.technobsoftwares.gpiec.modelo.Tipo_Patrimonio;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FrmInCadPatrimonio extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmInCadPatrimonio
     */
    public FrmInCadPatrimonio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCad = new javax.swing.JButton();
        btnCanc = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        cmbTipoPatr = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmbLocal = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        tpnPrincipal = new javax.swing.JTabbedPane();
        pnlGab = new javax.swing.JPanel();
        txtIpGab = new javax.swing.JTextField();
        rdbIp = new javax.swing.JRadioButton();
        txtNumSerieGab = new javax.swing.JTextField();
        cmbGab = new javax.swing.JComboBox();
        jLabel60 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeSistGab = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        pnlEstab = new javax.swing.JPanel();
        txtNumSerieEstab = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        cmbEstab = new javax.swing.JComboBox();
        pnlMonit = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        txtNumSerieMonit = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        cmbMonit = new javax.swing.JComboBox();
        txtNumPatr = new javax.swing.JTextField();

        btnCad.setText("Cadastrar");
        btnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadActionPerformed(evt);
            }
        });

        btnCanc.setText("Cancelar");
        btnCanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Patrimônio"));

        jLabel67.setText("Número de Patrimônio:");

        cmbTipoPatr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "*Tipo*" }));
        cmbTipoPatr.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cmbTipoPatrAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel3.setText("Tipo de Patrimônio:");

        cmbLocal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "*Locais*" }));
        cmbLocal.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cmbLocalAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel4.setText("Local:");

        txtIpGab.setEnabled(false);

        rdbIp.setText("Possui conexão com a rede");
        rdbIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbIpActionPerformed(evt);
            }
        });

        cmbGab.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "*Gabinete*", " " }));

        jLabel60.setText("Número de Série Fabricante:");

        jLabel2.setText("Gabinete:");

        jLabel61.setText("Nome no Sistema(Opcional):");

        jLabel62.setText("Número de IP:");

        javax.swing.GroupLayout pnlGabLayout = new javax.swing.GroupLayout(pnlGab);
        pnlGab.setLayout(pnlGabLayout);
        pnlGabLayout.setHorizontalGroup(
            pnlGabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGabLayout.createSequentialGroup()
                        .addGroup(pnlGabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel60)
                            .addComponent(jLabel61))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlGabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumSerieGab, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(txtNomeSistGab)))
                    .addGroup(pnlGabLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbGab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlGabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGabLayout.createSequentialGroup()
                        .addComponent(jLabel62)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIpGab)
                        .addGap(18, 18, 18))
                    .addGroup(pnlGabLayout.createSequentialGroup()
                        .addComponent(rdbIp)
                        .addContainerGap(41, Short.MAX_VALUE))))
        );
        pnlGabLayout.setVerticalGroup(
            pnlGabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGabLayout.createSequentialGroup()
                .addGroup(pnlGabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlGabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbGab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlGabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel60)
                            .addComponent(txtNumSerieGab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlGabLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(rdbIp)
                        .addGap(18, 18, 18)
                        .addGroup(pnlGabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIpGab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel62))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(txtNomeSistGab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        tpnPrincipal.addTab("Gabinete", pnlGab);

        jLabel63.setText("Número de Série Fabricante:");

        jLabel64.setText("Estabilizador:");

        cmbEstab.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "*Estabilizador*" }));

        javax.swing.GroupLayout pnlEstabLayout = new javax.swing.GroupLayout(pnlEstab);
        pnlEstab.setLayout(pnlEstabLayout);
        pnlEstabLayout.setHorizontalGroup(
            pnlEstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEstabLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(pnlEstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel63)
                    .addComponent(jLabel64))
                .addGap(18, 18, 18)
                .addGroup(pnlEstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbEstab, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNumSerieEstab, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109))
        );
        pnlEstabLayout.setVerticalGroup(
            pnlEstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel64)
                    .addComponent(cmbEstab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63)
                    .addComponent(txtNumSerieEstab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpnPrincipal.addTab("Estabilizador", pnlEstab);

        jLabel65.setText("Número de Fabricante:");

        jLabel66.setText("Monitor:");

        cmbMonit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "*Monitor*" }));

        javax.swing.GroupLayout pnlMonitLayout = new javax.swing.GroupLayout(pnlMonit);
        pnlMonit.setLayout(pnlMonitLayout);
        pnlMonitLayout.setHorizontalGroup(
            pnlMonitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMonitLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(pnlMonitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel65)
                    .addComponent(jLabel66))
                .addGap(18, 18, 18)
                .addGroup(pnlMonitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNumSerieMonit)
                    .addComponent(cmbMonit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        pnlMonitLayout.setVerticalGroup(
            pnlMonitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMonitLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMonitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66)
                    .addComponent(cmbMonit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlMonitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumSerieMonit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel65))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpnPrincipal.addTab("Monitor", pnlMonit);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(tpnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel67)
                    .addComponent(jLabel3))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(cmbTipoPatr, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtNumPatr, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cmbLocal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNumPatr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel67)
                                .addGap(18, 18, 18))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cmbTipoPatr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tpnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnCad)
                        .addGap(6, 6, 6)
                        .addComponent(btnCanc)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCad)
                    .addComponent(btnCanc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancActionPerformed

    private void rdbIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbIpActionPerformed
        if (rdbIp.isSelected()) {
            txtIpGab.setEnabled(true);
        } else{
            txtIpGab.setEnabled(false);
        }
    }//GEN-LAST:event_rdbIpActionPerformed

    private void btnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadActionPerformed
        if ("".equals(txtNumPatr.getText())) {
            JOptionPane.showMessageDialog(null, "Insira o número do patrimônio primeiro!");
        } else{
            if (pnlGab.isShowing()) {
                if ("".equals(txtNumSerieGab.getText())) {
                    JOptionPane.showMessageDialog(null, "Insira um número de série!");                
                } else{
                    if (rdbIp.isSelected()) {
                        if ("".equals(txtIpGab.getText())) {
                            JOptionPane.showMessageDialog(null, "Insira um número de IP ou desmarque a opção \"Possui conexão com a rede\"!");
                        } else{
                            txtNumPatr.setText("");
                            txtNumSerieGab.setText("");
                            txtIpGab.setText("");
                            JOptionPane.showMessageDialog(null, "Gabinete cadastrado com sucesso!");
                        }
                    }else{
                        txtNumPatr.setText("");
                        txtNumSerieGab.setText("");
                        JOptionPane.showMessageDialog(null, "Gabinete cadastrado com sucesso!");
                    }
                }
            }
            else if (pnlEstab.isShowing()) {
                if ("".equals(txtNumPatr.getText())) {
                    JOptionPane.showMessageDialog(null, "Insira o número do patrimônio primeiro!");
                }else{
                    if ("".equals(txtNumSerieEstab.getText())) {
                        JOptionPane.showMessageDialog(null, "Insira o número de série do estabilizador primeiro!");
                    }else{
                        txtNumPatr.setText("");
                        txtNumSerieEstab.setText("");
                        JOptionPane.showMessageDialog(null, "Estabilizador cadastrado com sucesso!");
                    }
                }
            }
            else{
                if ("".equals(txtNumPatr.getText())) {
                    JOptionPane.showMessageDialog(null, "Insira o número do patrimônio primeiro!");
                }else{
                    if ("".equals(txtNumSerieMonit.getText())) {
                        JOptionPane.showMessageDialog(null, "Insira o número de série do monitor primeiro!");
                    }else{
                        txtNumPatr.setText("");
                        txtNumSerieMonit.setText("");
                        JOptionPane.showMessageDialog(null, "Monitor cadastrado com sucesso!");
                    }
                }
            }
        }  
    }//GEN-LAST:event_btnCadActionPerformed

    private void cmbLocalAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cmbLocalAncestorAdded
        LocalDAO dao = new LocalDAO();
        List<Local> locais = dao.getLista();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cmbLocal.getModel();
        for (Local local : locais) {
            model.addElement(local.getNome_local());
        }
    }//GEN-LAST:event_cmbLocalAncestorAdded

    private void cmbTipoPatrAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cmbTipoPatrAncestorAdded
        Tipo_PatrimonioDAO dao = new Tipo_PatrimonioDAO();
        List<Tipo_Patrimonio> tipo_patrimonios = dao.getLista();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cmbTipoPatr.getModel();
        for (Tipo_Patrimonio tipo_patrimonio : tipo_patrimonios) {
            model.addElement(tipo_patrimonio.getTipo_patrimonio());
        }
    }//GEN-LAST:event_cmbTipoPatrAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCad;
    private javax.swing.JButton btnCanc;
    private javax.swing.JComboBox cmbEstab;
    private javax.swing.JComboBox cmbGab;
    private javax.swing.JComboBox cmbLocal;
    private javax.swing.JComboBox cmbMonit;
    private javax.swing.JComboBox cmbTipoPatr;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel pnlEstab;
    private javax.swing.JPanel pnlGab;
    private javax.swing.JPanel pnlMonit;
    private javax.swing.JRadioButton rdbIp;
    private javax.swing.JTabbedPane tpnPrincipal;
    private javax.swing.JTextField txtIpGab;
    private javax.swing.JTextField txtNomeSistGab;
    private javax.swing.JTextField txtNumPatr;
    private javax.swing.JTextField txtNumSerieEstab;
    private javax.swing.JTextField txtNumSerieGab;
    private javax.swing.JTextField txtNumSerieMonit;
    // End of variables declaration//GEN-END:variables
}
