/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.technobsoftwares.gpiec.formulario;

import br.com.technobsoftwares.gpiec.dao.LocalDAO;
import br.com.technobsoftwares.gpiec.modelo.Local;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lab
 */
public class FrmInConsLocal extends javax.swing.JInternalFrame {
    boolean alteracao = false;
    /**
     * Creates new form FrmInRelatLocal
     */
    public FrmInConsLocal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnAlt = new javax.swing.JButton();
        btnCons = new javax.swing.JButton();
        btnConAlt = new javax.swing.JButton();
        txtCons = new javax.swing.JTextField();
        btnExc = new javax.swing.JButton();
        lblMetodo = new javax.swing.JLabel();
        btnCanc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtLocal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDesc = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        cmbMetodo = new javax.swing.JComboBox();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de Locais"));

        jLabel8.setText("Método de Pesquisa:");

        btnAlt.setText("Alterar");
        btnAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltActionPerformed(evt);
            }
        });

        btnCons.setText("Consultar");
        btnCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsActionPerformed(evt);
            }
        });

        btnConAlt.setText("Confirmar Alteração");
        btnConAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConAltActionPerformed(evt);
            }
        });

        btnExc.setText("Excluir");
        btnExc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcActionPerformed(evt);
            }
        });

        lblMetodo.setText("Código:");

        btnCanc.setText("Cancelar");
        btnCanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancActionPerformed(evt);
            }
        });

        jLabel2.setText("Descrição:");

        jLabel1.setText("Local:*");

        txtLocal.setEnabled(false);

        txaDesc.setColumns(20);
        txaDesc.setLineWrap(true);
        txaDesc.setRows(5);
        txaDesc.setWrapStyleWord(true);
        txaDesc.setEnabled(false);
        jScrollPane1.setViewportView(txaDesc);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Local", "Descrição", "Quantidade de Máquinas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl);
        if (tbl.getColumnModel().getColumnCount() > 0) {
            tbl.getColumnModel().getColumn(3).setHeaderValue("Quantidade de Máquinas");
        }

        cmbMetodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código", "Local", "Descrição", "Qtd. Máquinas" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLocal)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnConAlt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnExc)
                                .addGap(32, 32, 32)
                                .addComponent(btnCanc)
                                .addGap(20, 20, 20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblMetodo)
                                .addGap(18, 18, 18)
                                .addComponent(txtCons, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCons)
                                .addGap(73, 73, 73)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(cmbMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCons)
                    .addComponent(lblMetodo)
                    .addComponent(cmbMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnExc)
                                    .addComponent(btnCanc))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btnAlt)
                        .addGap(18, 18, 18)
                        .addComponent(btnConAlt)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancActionPerformed

    private void btnConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsActionPerformed
        try {
            Local local = new Local();
            LocalDAO dao = new LocalDAO();
            local.setId_local(Integer.parseInt(txtCons.getText()));
            dao.pesquisar(local);
        
            txtLocal.setText(local.getNome_local());
            txaDesc.setText(local.getDesc_local());
            
            if (txtLocal.getText().equals("")) {
                txtCons.setText("");
                JOptionPane.showMessageDialog(null, "Local não cadastrado!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Insira um ID válido!");
        } 
    }//GEN-LAST:event_btnConsActionPerformed

    private void btnAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltActionPerformed
        if (!"".equals(txtLocal.getText())) {
            int resposta = JOptionPane.showConfirmDialog(null, "Deseja fazer essa alteração?");
            if (resposta == 0 ) {
                txtLocal.setEnabled(true);
                txaDesc.setEnabled(true);
                alteracao = true;
            }
            else if (resposta == 1) {
                txtLocal.setEnabled(false);
                txaDesc.setEnabled(false);
                boolean alteracao = false;
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Selecione um local primeiro!");
        }
    }//GEN-LAST:event_btnAltActionPerformed

    private void btnConAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConAltActionPerformed
        if (alteracao == true) {
            Local local = new Local();
            local.setId_local(Integer.parseInt(txtCons.getText()));
            local.setNome_local(txtLocal.getText());
            local.setDesc_local(txaDesc.getText());

            txtLocal.setEnabled(false);
            txaDesc.setEnabled(false);
            boolean alteracao = false;
            LocalDAO dao = new LocalDAO();
            dao.alterar(local);
            JOptionPane.showMessageDialog(null, "Dados alterados com sucesso!");
            tblAncestorAdded(null);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Realize uma alteração em um registro primeiro!");
        }
    }//GEN-LAST:event_btnConAltActionPerformed

    private void btnExcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcActionPerformed
        if ("".equals(txtLocal.getText())) {
            JOptionPane.showMessageDialog(null, "Selecione um registro primeiro!");
            txtCons.requestFocus();
        }
        else
        {
            Local local = new Local();
            int resposta=JOptionPane.showConfirmDialog(null, "Deseja mesmo excluir?");
            if (resposta == 0) {
                local.setId_local(Integer.parseInt(txtCons.getText()));
                LocalDAO dao = new LocalDAO();
                dao.deletar(local);
                JOptionPane.showMessageDialog(null, "Local removido com sucesso!");
                txtCons.setText("");
                txtLocal.setText("");
                txaDesc.setText("");
                tblAncestorAdded(null);
                txtCons.requestFocus();
            }
        }
    }//GEN-LAST:event_btnExcActionPerformed

    private void tblAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblAncestorAdded
        LocalDAO dao = new LocalDAO();
        List<Local> locais = dao.getLista();
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        model.setNumRows(0);
        for (Local local : locais) {
            model.addRow(new Object[]{
                local.getId_local(),
                local.getNome_local(),
                local.getDesc_local()
            });
        }
    }//GEN-LAST:event_tblAncestorAdded

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        if (evt.getClickCount() ==  1) {
            Local local = new Local();
            txtCons.setText(tbl.getValueAt(tbl.getSelectedRow(), 0).toString());
            txtLocal.setText(tbl.getValueAt(tbl.getSelectedRow(), 1).toString());
            txaDesc.setText(tbl.getValueAt(tbl.getSelectedRow(), 2).toString());
            
            LocalDAO dao = new LocalDAO();
            local.setId_local(Integer.parseInt(txtCons.getText()));
            dao.pesquisar(local);
        }
    }//GEN-LAST:event_tblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlt;
    private javax.swing.JButton btnCanc;
    private javax.swing.JButton btnConAlt;
    private javax.swing.JButton btnCons;
    private javax.swing.JButton btnExc;
    private javax.swing.JComboBox cmbMetodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMetodo;
    private javax.swing.JTable tbl;
    private javax.swing.JTextArea txaDesc;
    private javax.swing.JTextField txtCons;
    private javax.swing.JTextField txtLocal;
    // End of variables declaration//GEN-END:variables
}
