/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.technobsoftwares.gpiec.formulario;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author User
 */
public class FrmInOpcoes extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmInOpcoes
     */
    public FrmInOpcoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSalva = new javax.swing.JButton();
        btnCanc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbResolucao = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAltSenha = new javax.swing.JButton();
        psrConfSenha = new javax.swing.JPasswordField();
        psrNewSenha = new javax.swing.JPasswordField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Configurações"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalva.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSalva.setText("Salvar");
        jPanel1.add(btnSalva, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, 30));

        btnCanc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCanc.setText("Cancelar");
        btnCanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancActionPerformed(evt);
            }
        });
        jPanel1.add(btnCanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Resolução:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        cmbResolucao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbResolucao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "*RESOLUÇÃO*" }));
        cmbResolucao.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cmbResolucaoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(cmbResolucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 130, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Confirme sua senha:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));
        jLabel2.setVisible(false);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Nova senha:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));
        jLabel3.setVisible(false);

        btnAltSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAltSenha.setText("Alterar senha");
        btnAltSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAltSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, 40));

        psrConfSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(psrConfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 130, 30));
        psrConfSenha.setVisible(false);

        psrNewSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(psrNewSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 130, 30));
        psrNewSenha.setVisible(false);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 520, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancActionPerformed

    private void btnAltSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltSenhaActionPerformed
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        psrConfSenha.setVisible(true);
        psrNewSenha.setVisible(true);
    }//GEN-LAST:event_btnAltSenhaActionPerformed

    private void cmbResolucaoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cmbResolucaoAncestorAdded
        DefaultComboBoxModel model = (DefaultComboBoxModel) cmbResolucao.getModel();
        model.addElement(FrmMenuAdmin.width+"x"+FrmMenuAdmin.height);
    }//GEN-LAST:event_cmbResolucaoAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltSenha;
    private javax.swing.JButton btnCanc;
    private javax.swing.JButton btnSalva;
    private javax.swing.JComboBox cmbResolucao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField psrConfSenha;
    private javax.swing.JPasswordField psrNewSenha;
    // End of variables declaration//GEN-END:variables
}
