/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.technobsoftwares.gpiec.formulario;

import br.com.technobsoftwares.gpiec.dao.Ordem_de_ServicoDAO;
import br.com.technobsoftwares.gpiec.dao.UsuarioDAO;
import br.com.technobsoftwares.gpiec.modelo.Ordem_de_Servico;
import br.com.technobsoftwares.gpiec.modelo.Usuario;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author lab
 */
public class FrmMenuAdmin extends javax.swing.JFrame {
    FrmInCadUser cadastrouser = null;
    FrmInConsPatrimonio relatpatrim = null;
    FrmInCadPatrimonio cadastropatrim = null;
    FrmInAbreOS cadastroos = null;
    FrmInMinhasOS minhasos = null;
    FrmInConstOS relatos = null;
    FrmInCadHardware cadastrohardware = null;
    FrmInCadSoftware cadastrosoftware = null;
    FrmInCadLocal cadastrolocal = null;
    FrmInConsSoftware conssoftware = null;
    FrmInConsHardware conshardware = null;
    FrmInConsUser consuser = null;
    FrmInConsTipoUser consgrupo = null;
    FrmInConsLocal conslocal = null; 
    FrmInOpcoes opcoes = null;
    FrmInGerenciaOS gerenciaos = null;  
    FrmInCadTipoUser cadtipouser = null;
    public static int width;
    public static int height;
    /**
     * Creates new form FrmMenu
     */
    public FrmMenuAdmin() {
        initComponents(); 
        
        this.setExtendedState(FrmMenuAdmin.MAXIMIZED_BOTH);
        jDesktopPane1.setMaximumSize(this.getMaximumSize());    
        //tester();
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        width = (int) screenSize.getWidth();
        height = (int) screenSize.getHeight();  
        this.setSize((int)width,(int)height);
        this.setExtendedState(FrmMenuAdmin.MAXIMIZED_BOTH);      
    }
    
    public void tester(){
        UsuarioDAO grupos = new UsuarioDAO();
        if (grupos.cad_user == false) {
            jMenuItem1.setEnabled(false);
        }
        if (grupos.cad_patrimonio == false) {
            jMenuItem7.setEnabled(false);
        }
        if (grupos.cad_local == false) {
            jMenuItem11.setEnabled(false);
        }
        if (grupos.cad_soft == false) {
            jMenuItem8.setEnabled(false);
        }
        if (grupos.cad_hard == false) {
            jMenuItem12.setEnabled(false);
        }
        
        if (grupos.cons_user == false) {
            jMenuItem5.setEnabled(false);
        }
        if (grupos.cons_grupo == false) {
            jMenuItem14.setEnabled(false);
        }
        if (grupos.cons_patrimonio == false) {
            jMenuItem9.setEnabled(false);
        }
        if (grupos.cons_local == false) {
            jMenuItem15.setEnabled(false);
        }
        if (grupos.cons_soft == false) {
            jMenuItem10.setEnabled(false);
        }
        if (grupos.cons_hard == false) {
            jMenuItem13.setEnabled(false);
        }
        
        if (grupos.relat_user == false) {
            jMenuItem2.setEnabled(false);
        }
        if (grupos.relat_grupo == false) {
            jMenuItem19.setEnabled(false);
        }
        if (grupos.relat_patrimonio == false) {
            jMenuItem23.setEnabled(false);
        }
        if (grupos.relat_local == false) {
            jMenuItem25.setEnabled(false);
        }
        if (grupos.relat_soft == false) {
            jMenuItem26.setEnabled(false);
        }
        if (grupos.relat_hard == false) {
            jMenuItem27.setEnabled(false);
        }

        if (grupos.abrir_os == false) {
            jMenuItem4.setEnabled(false);
            jMenuItem3.setEnabled(false);
        }
        if (grupos.fechar_os == false) {
            jMenuItem16.setEnabled(false);
        }
        if (grupos.edit_os == false) {
            jMenuItem6.setEnabled(false);
        }
        if (grupos.relat_os == false) {
            jMenuItem24.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        menuConfig = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(720, 450));

        jButton1.setText("Deslogar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(1009, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(530, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu9.setText("Cadastro");

        jMenuItem1.setText("Usuário");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem1);

        jMenuItem17.setText("Grupo");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem17);

        jMenuItem7.setText("Patrimônio");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem7);

        jMenuItem11.setText("Local");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem11);

        jMenuItem8.setText("Software");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem8);

        jMenuItem12.setText("Hardware");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem12);

        jMenuBar1.add(jMenu9);

        jMenu10.setText("Consulta");

        jMenuItem5.setText("Usuário");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem5);

        jMenuItem14.setText("Grupos de Usuários");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem14);

        jMenuItem9.setText("Patrimônio");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem9);

        jMenuItem6.setText("Ordem de Serviço");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem6);

        jMenuItem15.setText("Local");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem15);

        jMenuItem10.setText("Software");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem10);

        jMenuItem13.setText("Hardware");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem13);

        jMenuBar1.add(jMenu10);

        jMenu11.setText("Relatório");

        jMenuItem2.setText("Usuário");
        jMenu11.add(jMenuItem2);

        jMenuItem19.setText("Grupos de Usuário");
        jMenu11.add(jMenuItem19);

        jMenuItem23.setText("Patrimônio");
        jMenu11.add(jMenuItem23);

        jMenuItem24.setText("Ordem de Serviço");
        jMenu11.add(jMenuItem24);

        jMenuItem25.setText("Local");
        jMenu11.add(jMenuItem25);

        jMenuItem26.setText("Software");
        jMenu11.add(jMenuItem26);

        jMenuItem27.setText("Hardware");
        jMenu11.add(jMenuItem27);

        jMenuBar1.add(jMenu11);

        jMenu4.setText("Ordem de Serviço");

        jMenuItem4.setText("Abrir O.S");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem3.setText("Minhas O.S");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem16.setText("O.S não fechadas");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem16);

        jMenuBar1.add(jMenu4);

        menuConfig.setText("Configurações");
        menuConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuConfigMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuConfig);

        jMenu1.setText("Sair");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1094, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            if (evt.getSource() == jMenuItem1) {
                if (cadastrouser == null) {
                    cadastrouser = new FrmInCadUser();
                    jDesktopPane1.add(cadastrouser);
                    cadastrouser.setVisible(true);
//                    cadastrouser.setMaximum(true);
                }
            jDesktopPane1.moveToFront(cadastrouser);
            }
            if (cadastrouser.isClosed()) {
                cadastrouser = new FrmInCadUser();
                jDesktopPane1.add(cadastrouser);
                cadastrouser.setVisible(true);
                jDesktopPane1.moveToFront(cadastrouser);
//                cadastrouser.setMaximum(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }  
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        try {
            if (evt.getSource() == jMenuItem9) {
                if (relatpatrim == null) {
                    relatpatrim = new FrmInConsPatrimonio();
                    jDesktopPane1.add(relatpatrim);
                    relatpatrim.setVisible(true);
//                    relatpatrim.setMaximum(true);
                }
            jDesktopPane1.moveToFront(relatpatrim);
            }
            if (relatpatrim.isClosed()) {
                relatpatrim = new FrmInConsPatrimonio();
                jDesktopPane1.add(relatpatrim);
                relatpatrim.setVisible(true);
                jDesktopPane1.moveToFront(relatpatrim);
//                relatpatrim.setMaximum(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }  
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        try {
            if (evt.getSource() == jMenuItem7) {
                if (cadastropatrim == null) {
                    cadastropatrim = new FrmInCadPatrimonio();
                    jDesktopPane1.add(cadastropatrim);
                    cadastropatrim.setVisible(true);
//                    cadastropatrim.setMaximum(true);
                }
            jDesktopPane1.moveToFront(cadastropatrim);
            }
            if (cadastropatrim.isClosed()) {
                cadastropatrim = new FrmInCadPatrimonio();
                jDesktopPane1.add(cadastropatrim);
                cadastropatrim.setVisible(true);
                jDesktopPane1.moveToFront(cadastropatrim);
//                cadastropatrim.setMaximum(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }  
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        try {
            if (evt.getSource() == jMenuItem6) {
                if (relatos == null) {
                    relatos = new FrmInConstOS();
                    jDesktopPane1.add(relatos);
                    relatos.setVisible(true);
//                    relatos.setMaximum(true);
                }
            jDesktopPane1.moveToFront(relatos);
            }
            if (relatos.isClosed()) {
                relatos = new FrmInConstOS();
                jDesktopPane1.add(relatos);
                relatos.setVisible(true);
                jDesktopPane1.moveToFront(relatos);
//                relatos.setMaximum(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }  
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        try {
            if (evt.getSource() == jMenuItem8) {
                if (cadastrosoftware == null) {
                    cadastrosoftware = new FrmInCadSoftware();
                    jDesktopPane1.add(cadastrosoftware);
                    cadastrosoftware.setVisible(true);
//                    relatos.setMaximum(true);
                }
            jDesktopPane1.moveToFront(cadastrosoftware);
            }
            if (cadastrosoftware.isClosed()) {
                cadastrosoftware = new FrmInCadSoftware();
                jDesktopPane1.add(cadastrosoftware);
                cadastrosoftware.setVisible(true);
                jDesktopPane1.moveToFront(cadastrosoftware);
//                relatos.setMaximum(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } 
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        try {
            if (evt.getSource() == jMenuItem11) {
                if (cadastrolocal == null) {
                    cadastrolocal = new FrmInCadLocal();
                    jDesktopPane1.add(cadastrolocal);
                    cadastrolocal.setVisible(true);
//                    relatos.setMaximum(true);
                }
            jDesktopPane1.moveToFront(cadastrolocal);
            }
            if (cadastrolocal.isClosed()) {
                cadastrolocal = new FrmInCadLocal();
                jDesktopPane1.add(cadastrolocal);
                cadastrolocal.setVisible(true);
                jDesktopPane1.moveToFront(cadastrolocal);
//                relatos.setMaximum(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } 
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        try {
            if (evt.getSource() == jMenuItem10) {
                if (conssoftware == null) {
                    conssoftware = new FrmInConsSoftware();
                    jDesktopPane1.add(conssoftware);
                    conssoftware.setVisible(true);
//                    relatos.setMaximum(true);
                }
            jDesktopPane1.moveToFront(conssoftware);
            }
            if (conssoftware.isClosed()) {
                conssoftware = new FrmInConsSoftware();
                jDesktopPane1.add(conssoftware);
                conssoftware.setVisible(true);
                jDesktopPane1.moveToFront(conssoftware);
//                relatos.setMaximum(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } 
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        try {
            if (evt.getSource() == jMenuItem12) {
                if (cadastrohardware == null) {
                    cadastrohardware = new FrmInCadHardware();
                    jDesktopPane1.add(cadastrohardware);
                    cadastrohardware.setVisible(true);
//                    relatos.setMaximum(true);
                }
            jDesktopPane1.moveToFront(cadastrohardware);
            }
            if (cadastrohardware.isClosed()) {
                cadastrohardware = new FrmInCadHardware();
                jDesktopPane1.add(cadastrohardware);
                cadastrohardware.setVisible(true);
                jDesktopPane1.moveToFront(cadastrohardware);
//                relatos.setMaximum(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } 
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        try {
            if (evt.getSource() == jMenuItem13) {
                if (conshardware == null) {
                    conshardware = new FrmInConsHardware();
                    jDesktopPane1.add(conshardware);
                    conshardware.setVisible(true);
//                    relatos.setMaximum(true);
                }
            jDesktopPane1.moveToFront(conshardware);
            }
            if (conshardware.isClosed()) {
                conshardware = new FrmInConsHardware();
                jDesktopPane1.add(conshardware);
                conshardware.setVisible(true);
                jDesktopPane1.moveToFront(conshardware);
//                relatos.setMaximum(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } 
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        try {
            if (evt.getSource() == jMenuItem5) {
                if (consuser == null) {
                    consuser = new FrmInConsUser();
                    jDesktopPane1.add(consuser);
                    consuser.setVisible(true);
//                    relatos.setMaximum(true);
                }
            jDesktopPane1.moveToFront(consuser);
            }
            if (consuser.isClosed()) {
                consuser = new FrmInConsUser();
                jDesktopPane1.add(consuser);
                consuser.setVisible(true);
                jDesktopPane1.moveToFront(consuser);
//                relatos.setMaximum(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } 
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        try {
            if (evt.getSource() == jMenuItem14) {
                if (consgrupo == null) {
                    consgrupo = new FrmInConsTipoUser();
                    jDesktopPane1.add(consgrupo);
                    consgrupo.setVisible(true);
//                    relatos.setMaximum(true);
                }
            jDesktopPane1.moveToFront(consgrupo);
            }
            if (consgrupo.isClosed()) {
                consgrupo = new FrmInConsTipoUser();
                jDesktopPane1.add(consgrupo);
                consgrupo.setVisible(true);
                jDesktopPane1.moveToFront(consgrupo);
//                relatos.setMaximum(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } 
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        try {
            if (evt.getSource() == jMenuItem15) {
                if (conslocal == null) {
                    conslocal = new FrmInConsLocal();
                    jDesktopPane1.add(conslocal);
                    conslocal.setVisible(true);
//                    relatos.setMaximum(true);
                }
            jDesktopPane1.moveToFront(conslocal);
            }
            if (conslocal.isClosed()) {
                conslocal = new FrmInConsLocal();
                jDesktopPane1.add(conslocal);
                conslocal.setVisible(true);
                jDesktopPane1.moveToFront(conslocal);
//                relatos.setMaximum(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } 
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new FrmLogin().show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            if (evt.getSource() == jMenuItem3) {
                if (minhasos == null) {
                    minhasos = new FrmInMinhasOS();
                    jDesktopPane1.add(minhasos);
                    minhasos.setVisible(true);
                    //                    fechaos.setMaximum(true);
                }
                jDesktopPane1.moveToFront(minhasos);
            }
            if (minhasos.isClosed()) {
                minhasos = new FrmInMinhasOS();
                jDesktopPane1.add(minhasos);
                minhasos.setVisible(true);
                jDesktopPane1.moveToFront(minhasos);
                //                fechaos.setMaximum(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try {
            if (evt.getSource() == jMenuItem4) {
                if (cadastroos == null) {
                    cadastroos = new FrmInAbreOS();
                    jDesktopPane1.add(cadastroos);
                    cadastroos.setVisible(true);
                    //                    cadastroos.setMaximum(true);
                }
                jDesktopPane1.moveToFront(cadastroos);
            }
            if (cadastroos.isClosed()) {
                cadastroos = new FrmInAbreOS();
                jDesktopPane1.add(cadastroos);
                cadastroos.setVisible(true);
                jDesktopPane1.moveToFront(cadastroos);
                //                cadastroos.setMaximum(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void menuConfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuConfigMouseClicked
        try {
            if (evt.getSource() == menuConfig) {
                if (opcoes == null) {
                    opcoes = new FrmInOpcoes();
                    jDesktopPane1.add(opcoes);
                    opcoes.setVisible(true);
                    //                    cadastroos.setMaximum(true);
                }
                jDesktopPane1.moveToFront(opcoes);
            }
            if (opcoes.isClosed()) {
                opcoes = new FrmInOpcoes();
                jDesktopPane1.add(opcoes);
                opcoes.setVisible(true);
                jDesktopPane1.moveToFront(opcoes);
                //                cadastroos.setMaximum(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_menuConfigMouseClicked

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        try {
            if (evt.getSource() == jMenuItem16) {
                if (gerenciaos == null) {
                    gerenciaos = new FrmInGerenciaOS();
                    jDesktopPane1.add(gerenciaos);
                    gerenciaos.setVisible(true);
                    //                    cadastroos.setMaximum(true);
                }
                jDesktopPane1.moveToFront(gerenciaos);
            }
            if (gerenciaos.isClosed()) {
                gerenciaos = new FrmInGerenciaOS();
                jDesktopPane1.add(gerenciaos);
                gerenciaos.setVisible(true);
                jDesktopPane1.moveToFront(gerenciaos);
                //                cadastroos.setMaximum(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        try {
            if (evt.getSource() == jMenuItem17) {
                if (cadtipouser == null) {
                    cadtipouser = new FrmInCadTipoUser();
                    jDesktopPane1.add(cadtipouser);
                    cadtipouser.setVisible(true);
                    //                    cadastroos.setMaximum(true);
                }
                jDesktopPane1.moveToFront(cadtipouser);
            }
            if (cadtipouser.isClosed()) {
                cadtipouser = new FrmInCadTipoUser();
                jDesktopPane1.add(cadtipouser);
                cadtipouser.setVisible(true);
                jDesktopPane1.moveToFront(cadtipouser);
                //                cadastroos.setMaximum(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu menuConfig;
    // End of variables declaration//GEN-END:variables
}
