/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.technobsoftwares.gpiec.formulario;

import br.com.technobsoftwares.gpiec.dao.Local_2DAO;
import br.com.technobsoftwares.gpiec.dao.TipopatrimonioDAO;
import br.com.technobsoftwares.gpiec.modelo.Local_2;
import br.com.technobsoftwares.gpiec.modelo.Tipopatrimonio;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FrmInCadPatrimonio extends javax.swing.JInternalFrame {
    /**
     * Creates new form FrmInCadPatrimonio
     */
    public FrmInCadPatrimonio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        cmbTipoPatr = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmbLocal = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        tpnPrincipal = new javax.swing.JTabbedPane();
        pnlEstab = new javax.swing.JPanel();
        txtNumSerieEstab = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        cmbEstab = new javax.swing.JComboBox();
        pnlMonit = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        txtNumSerieMonit = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        cmbMonit = new javax.swing.JComboBox();
        pnlGab = new javax.swing.JPanel();
        txtIpGab = new javax.swing.JTextField();
        rdbIp = new javax.swing.JRadioButton();
        txtNumSerieGab = new javax.swing.JTextField();
        cmbGab = new javax.swing.JComboBox();
        jLabel60 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeSistGab = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        txtNumPatr = new javax.swing.JTextField();
        btnCanc = new javax.swing.JButton();
        btnCad = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Patrimônio"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel67.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel67.setText("Número de Patrimônio:");
        jPanel4.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        cmbTipoPatr.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbTipoPatr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "*Tipo*" }));
        cmbTipoPatr.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cmbTipoPatrAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel4.add(cmbTipoPatr, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 150, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Tipo de Patrimônio:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        cmbLocal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbLocal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "*Locais*" }));
        cmbLocal.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cmbLocalAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel4.add(cmbLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 200, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Local:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        pnlEstab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNumSerieEstab.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlEstab.add(txtNumSerieEstab, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 140, 30));

        jLabel63.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel63.setText("Número de Série Fabricante:*");
        pnlEstab.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel64.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel64.setText("Estabilizador:*");
        pnlEstab.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        cmbEstab.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbEstab.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "*Estabilizador*" }));
        pnlEstab.add(cmbEstab, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 140, 30));

        tpnPrincipal.addTab("Estabilizador", pnlEstab);

        pnlMonit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel65.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel65.setText("Número de Fabricante:*");
        pnlMonit.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        txtNumSerieMonit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlMonit.add(txtNumSerieMonit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 150, 30));

        jLabel66.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel66.setText("Monitor:*");
        pnlMonit.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        cmbMonit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbMonit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "*Monitor*" }));
        pnlMonit.add(cmbMonit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 150, 30));

        tpnPrincipal.addTab("Monitor", pnlMonit);

        pnlGab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIpGab.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtIpGab.setEnabled(false);
        pnlGab.add(txtIpGab, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 185, 30));

        rdbIp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rdbIp.setText("Possui conexão com a rede");
        rdbIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbIpActionPerformed(evt);
            }
        });
        pnlGab.add(rdbIp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, 30));

        txtNumSerieGab.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlGab.add(txtNumSerieGab, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 160, 30));

        cmbGab.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbGab.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "*Gabinete*", "Novo..." }));
        pnlGab.add(cmbGab, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 140, 30));

        jLabel60.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel60.setText("Número de Série Fabricante:*");
        pnlGab.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Gabinete:*");
        pnlGab.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        txtNomeSistGab.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlGab.add(txtNomeSistGab, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 160, 30));

        jLabel61.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel61.setText("Nome no Sistema:*");
        pnlGab.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel62.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel62.setText("Número de IP:*");
        pnlGab.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        tpnPrincipal.addTab("Gabinete", pnlGab);

        jPanel4.add(tpnPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 590, 270));

        txtNumPatr.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel4.add(txtNumPatr, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 140, 30));

        btnCanc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCanc.setText("Sair");
        btnCanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancActionPerformed(evt);
            }
        });
        jPanel4.add(btnCanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, -1, 30));

        btnCad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCad.setText("Cadastrar");
        btnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadActionPerformed(evt);
            }
        });
        jPanel4.add(btnCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, -1, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 610, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancActionPerformed

    private void rdbIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbIpActionPerformed
        if (rdbIp.isSelected()) {
            txtIpGab.setEnabled(true);
        } else{
            txtIpGab.setEnabled(false);
        }
    }//GEN-LAST:event_rdbIpActionPerformed

    private void btnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadActionPerformed
        if ("".equals(txtNumPatr.getText())) {
            JOptionPane.showMessageDialog(null, "Insira o número do patrimônio primeiro!");
        } else{
            if (pnlGab.isShowing()) {
                if ("".equals(txtNumSerieGab.getText())) {
                    JOptionPane.showMessageDialog(null, "Insira um número de série!");                
                } else{
                    if (rdbIp.isSelected()) {
                        if ("".equals(txtIpGab.getText())) {
                            JOptionPane.showMessageDialog(null, "Insira um número de IP ou desmarque a opção \"Possui conexão com a rede\"!");
                        } else{
                            txtNumPatr.setText("");
                            txtNumSerieGab.setText("");
                            txtIpGab.setText("");
                            JOptionPane.showMessageDialog(null, "Gabinete cadastrado com sucesso!");
                        }
                    }else{
                        txtNumPatr.setText("");
                        txtNumSerieGab.setText("");
                        JOptionPane.showMessageDialog(null, "Gabinete cadastrado com sucesso!");
                    }
                }
            }
            else if (pnlEstab.isShowing()) {
                if ("".equals(txtNumPatr.getText())) {
                    JOptionPane.showMessageDialog(null, "Insira o número do patrimônio primeiro!");
                }else{
                    if ("".equals(txtNumSerieEstab.getText())) {
                        JOptionPane.showMessageDialog(null, "Insira o número de série do estabilizador primeiro!");
                    }else{
                        txtNumPatr.setText("");
                        txtNumSerieEstab.setText("");
                        JOptionPane.showMessageDialog(null, "Estabilizador cadastrado com sucesso!");
                    }
                }
            }
            else{
                if ("".equals(txtNumPatr.getText())) {
                    JOptionPane.showMessageDialog(null, "Insira o número do patrimônio primeiro!");
                }else{
                    if ("".equals(txtNumSerieMonit.getText())) {
                        JOptionPane.showMessageDialog(null, "Insira o número de série do monitor primeiro!");
                    }else{
                        txtNumPatr.setText("");
                        txtNumSerieMonit.setText("");
                        JOptionPane.showMessageDialog(null, "Monitor cadastrado com sucesso!");
                    }
                }
            }
        }  
    }//GEN-LAST:event_btnCadActionPerformed

    private void cmbLocalAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cmbLocalAncestorAdded
        Local_2DAO dao = new Local_2DAO();
        List<Local_2> locais = dao.getLista();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cmbLocal.getModel();
        for (Local_2 local : locais) {
            model.addElement(local.getNome_local());
        }
    }//GEN-LAST:event_cmbLocalAncestorAdded

    private void cmbTipoPatrAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cmbTipoPatrAncestorAdded
        TipopatrimonioDAO dao = new TipopatrimonioDAO();
        List<Tipopatrimonio> tipo_patrimonios = dao.getLista();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cmbTipoPatr.getModel();
        for (Tipopatrimonio tipo_patrimonio : tipo_patrimonios) {
            model.addElement(tipo_patrimonio.getTipo());
        }
    }//GEN-LAST:event_cmbTipoPatrAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCad;
    private javax.swing.JButton btnCanc;
    private javax.swing.JComboBox cmbEstab;
    private javax.swing.JComboBox cmbGab;
    private javax.swing.JComboBox cmbLocal;
    private javax.swing.JComboBox cmbMonit;
    private javax.swing.JComboBox cmbTipoPatr;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel pnlEstab;
    private javax.swing.JPanel pnlGab;
    private javax.swing.JPanel pnlMonit;
    private javax.swing.JRadioButton rdbIp;
    private javax.swing.JTabbedPane tpnPrincipal;
    private javax.swing.JTextField txtIpGab;
    private javax.swing.JTextField txtNomeSistGab;
    private javax.swing.JTextField txtNumPatr;
    private javax.swing.JTextField txtNumSerieEstab;
    private javax.swing.JTextField txtNumSerieGab;
    private javax.swing.JTextField txtNumSerieMonit;
    // End of variables declaration//GEN-END:variables
}
