/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.technobsoftwares.gpiec.formulario;

import br.com.technobsoftwares.gpiec.dao.Local_2DAO;
import br.com.technobsoftwares.gpiec.modelo.Local_2;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author lab
 */
public class FrmInCadLocal extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmInCadLocal
     */
    public FrmInCadLocal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtLocal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCad = new javax.swing.JButton();
        btnCanc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDesc = new javax.swing.JTextArea();
        btnLimpar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Locais"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLocal.setDocument(new UpperCaseDocument());
        txtLocal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtLocal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TeclaPressionada(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ApenasTexto(evt);
            }
        });
        jPanel1.add(txtLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 230, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Local:*");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        btnCad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCad.setText("Cadastrar");
        btnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadActionPerformed(evt);
            }
        });
        jPanel1.add(btnCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, 30));

        btnCanc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCanc.setText("Sair");
        btnCanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancActionPerformed(evt);
            }
        });
        jPanel1.add(btnCanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Descrição:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        txaDesc.setColumns(20);
        txaDesc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txaDesc.setLineWrap(true);
        txaDesc.setRows(5);
        txaDesc.setWrapStyleWord(true);
        txaDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TeclaPressionada(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ApenasTexto(evt);
            }
        });
        jScrollPane1.setViewportView(txaDesc);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 230, -1));

        btnLimpar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLimpar.setText("Limpar");
        jPanel1.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, 30));

        jLabel3.setText("* = campos obrigatórios");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 430, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancActionPerformed

    private void btnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadActionPerformed
        try{
            if (!"".equals(txtLocal.getText())) {
                Local_2 local = new Local_2();
                local.setNome_local(txtLocal.getText());
                if ("".equals(txaDesc.getText())) {
                    local.setDesc_local("VAZIO");
                }else{
                    local.setDesc_local(txaDesc.getText());            
                }

                Local_2DAO dao = new Local_2DAO();
                dao.adiciona(local);

                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
                txtLocal.setText("");
                txaDesc.setText("");
                txtLocal.requestFocus();
            }else{
                JOptionPane.showMessageDialog(null, "Preencha o campo \"Local\"!");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Local já cadastrado!");
        }
    }//GEN-LAST:event_btnCadActionPerformed

    private void ApenasTexto(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ApenasTexto
        String caracteres="!@#$%¨&*()/\\*-+.,{}[]<>;:?°ºª'|\"=_`^~´¬§¢£³²¹°ºª";
        if(caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_ApenasTexto

    private void TeclaPressionada(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TeclaPressionada
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnCadActionPerformed(null);
        }
    }//GEN-LAST:event_TeclaPressionada


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCad;
    private javax.swing.JButton btnCanc;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaDesc;
    private javax.swing.JTextField txtLocal;
    // End of variables declaration//GEN-END:variables
}
