/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.technobsoftwares.gpiec.formulario;

import br.com.technobsoftwares.gpiec.dao.PcDAO;
import br.com.technobsoftwares.gpiec.dao.Local_2DAO;
import br.com.technobsoftwares.gpiec.dao.Ordem_de_ServicoDAO;
import br.com.technobsoftwares.gpiec.dao.TipoproblemaDAO;
import br.com.technobsoftwares.gpiec.dao.UsuarioDAO;
import br.com.technobsoftwares.gpiec.modelo.Pc;
import br.com.technobsoftwares.gpiec.modelo.Local_2;
import br.com.technobsoftwares.gpiec.modelo.Ordem_de_Servico;
import br.com.technobsoftwares.gpiec.modelo.Tipoproblema;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FrmInAbreOS extends javax.swing.JInternalFrame {
    //usada no método de verificação de pc na hora de logar
    public static String nome_pc, nome_servico, nome_local;
    
    /**
     * Creates new form FrmInCadOS
     */
    public FrmInAbreOS() {
        initComponents();
        //cmbLocal.setSelectedIndex(os);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cmbServiço = new javax.swing.JComboBox();
        txtJustif = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaDesc = new javax.swing.JTextArea();
        cmbLocal = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        btnSend = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmbComp = new javax.swing.JComboBox();
        btnCanc = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Abertura de O.S"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Serviço:*");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        cmbServiço.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbServiço.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "*SERVIÇO*" }));
        cmbServiço.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbServiçoItemStateChanged(evt);
            }
        });
        cmbServiço.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cmbServiçoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(cmbServiço, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 180, 30));

        txtJustif.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtJustif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ApenasTexto(evt);
            }
        });
        txtJustif.setDocument(new UpperCaseDocument());
        jPanel1.add(txtJustif, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 180, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Titulo:*");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Descrição:*");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        txtaDesc.setColumns(20);
        txtaDesc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtaDesc.setLineWrap(true);
        txtaDesc.setRows(5);
        txtaDesc.setWrapStyleWord(true);
        txtaDesc.setDocument(new UpperCaseDocument());
        txtaDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ApenasTexto(evt);
            }
        });
        jScrollPane1.setViewportView(txtaDesc);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 300, 100));

        cmbLocal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbLocal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "*LOCAL*" }));
        cmbLocal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbLocalItemStateChanged(evt);
            }
        });
        cmbLocal.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cmbLocalAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(cmbLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 180, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Local:*");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        btnSend.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSend.setText("Enviar");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        jPanel1.add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, 30));

        btnLimpar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Computador:*");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        cmbComp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbComp.setEnabled(false);
        cmbComp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCompItemStateChanged(evt);
            }
        });
        cmbComp.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cmbCompAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(cmbComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 180, 30));

        btnCanc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCanc.setText("Sair");
        btnCanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancActionPerformed(evt);
            }
        });
        jPanel1.add(btnCanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, -1, 30));

        jLabel6.setText("* = campos obrigatórios");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 6, 650, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtJustif.setText("");
        txtaDesc.setText("");
        cmbComp.setSelectedIndex(0);
        cmbLocal.setSelectedIndex(0);
        cmbServiço.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancActionPerformed

    private void cmbLocalAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cmbLocalAncestorAdded
        Local_2DAO dao = new Local_2DAO();
        List<Local_2> locais = dao.getLista();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cmbLocal.getModel();
        for (Local_2 local : locais) {
            model.addElement(local.getNome_local());
        }
    }//GEN-LAST:event_cmbLocalAncestorAdded

    private void cmbLocalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbLocalItemStateChanged
        if (cmbLocal.getSelectedIndex()!= 0) {
            //cmbComp.removeAllItems();
            //nome_local = String.valueOf(cmbLocal.getSelectedItem());           
            //local.setId_local(cmbLocal.getSelectedIndex());
            //os = cmbLocal.getSelectedIndex();
            cmbComp.setEnabled(true);
            cmbCompAncestorAdded(null);
        }else{
            cmbComp.removeAllItems();
            cmbComp.setEnabled(false);            
        }
    }//GEN-LAST:event_cmbLocalItemStateChanged

    private void cmbServiçoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cmbServiçoAncestorAdded
        TipoproblemaDAO dao = new TipoproblemaDAO();
        List<Tipoproblema> tproblemas = dao.getLista();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cmbServiço.getModel();
        for (Tipoproblema tproblema : tproblemas) {
            model.addElement(tproblema.getTipo_problema());
        }
    }//GEN-LAST:event_cmbServiçoAncestorAdded

    private void cmbCompAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cmbCompAncestorAdded
        nome_local = String.valueOf(cmbLocal.getSelectedItem()); 
        PcDAO dao = new PcDAO();
        Local_2 local = new Local_2();
        cmbComp.removeAllItems();
        dao.pesquisa_local(local);
        List<Pc> computadores = dao.getLista();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cmbComp.getModel();
        for (Pc computador : computadores) {
            model.addElement(computador.getNome_pc());
        }
    }//GEN-LAST:event_cmbCompAncestorAdded

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        UsuarioDAO dao = new UsuarioDAO();
        Ordem_de_ServicoDAO dao2 = new Ordem_de_ServicoDAO();
        
        if ((cmbComp.getSelectedItem() != "*COMPUTADOR*") && (cmbLocal.getSelectedIndex() != 0) && 
                (cmbServiço.getSelectedIndex() != 0) && (!"".equals(txtJustif.getText()))) {
            
            Ordem_de_Servico os = new Ordem_de_Servico();
            //os.setFk_id_pc(cmbComp.getSelectedIndex());
            os.setFk_id_pc(dao2.teste_id_os);
            //nome_pc = String.valueOf(cmbComp.getSelectedItem());
            os.setFk_id_usuario(dao.idloginuser);
            os.setFk_id_tipo_problema(dao2.teste_id_servico);
            os.setFk_id_status(1);
            os.setTitulo_os(txtJustif.getText());
            os.setDetalhes_os(txtaDesc.getText());
            
            dao2.adiciona(os);
            //JOptionPane.showMessageDialog(null, os.getFk_id_pc()+" / "+os.getFk_id_usuario()+" / "
                    //+os.getFk_id_tipo_problema()+" / "+os.getTitulo_os()+" / "+os.getDetalhes_os());
            cmbComp.setSelectedIndex(0);
            cmbLocal.setSelectedIndex(0);
            cmbServiço.setSelectedIndex(0);
            txtJustif.setText("");
            txtaDesc.setText("");
            cmbComp.setEnabled(false);
                        
            cmbComp.removeAllItems();
            JOptionPane.showMessageDialog(null, "Ordem de Serviço registrada com sucesso!");   
        } else {
            JOptionPane.showMessageDialog(null, "Insira os dados corretamente e selecione as opções!");
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void cmbCompItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCompItemStateChanged
        nome_pc = String.valueOf(cmbComp.getSelectedItem());
        Ordem_de_ServicoDAO dao = new Ordem_de_ServicoDAO();
        Ordem_de_Servico os = new Ordem_de_Servico();
        dao.pesquisa_pc(os);
    }//GEN-LAST:event_cmbCompItemStateChanged

    private void ApenasTexto(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ApenasTexto
        String caracteres="0123456789!@#$%¨&*()/\\*-+{}[]<>;:?°ºª'|\"=_`^~´¬§¢£³²¹°ºª";
        if(caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_ApenasTexto

    private void cmbServiçoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbServiçoItemStateChanged
        nome_servico = String.valueOf(cmbServiço.getSelectedItem());
        Ordem_de_ServicoDAO dao = new Ordem_de_ServicoDAO();
        Ordem_de_Servico os = new Ordem_de_Servico();
        dao.pesquisa_servico(os);
    }//GEN-LAST:event_cmbServiçoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCanc;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSend;
    private javax.swing.JComboBox cmbComp;
    private javax.swing.JComboBox cmbLocal;
    private javax.swing.JComboBox cmbServiço;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtJustif;
    private javax.swing.JTextArea txtaDesc;
    // End of variables declaration//GEN-END:variables
}
