/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.technobsoftwares.gpiec.formulario;

import br.com.technobsoftwares.gpiec.dao.PesquisaDAO;
import br.com.technobsoftwares.gpiec.dao.TipousuarioDAO;
import br.com.technobsoftwares.gpiec.dao.UsuarioDAO;
import br.com.technobsoftwares.gpiec.modelo.Pesquisa;
import br.com.technobsoftwares.gpiec.modelo.Tipousuario;
import br.com.technobsoftwares.gpiec.modelo.Usuario;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author lab
 */
public class FrmInConsUser extends javax.swing.JInternalFrame {
    boolean alteracao = false;
    /**
     * Creates new form FrmInRelatUser
     */
    public static String teste;
    public FrmInConsUser() {
        initComponents();
        fmtConsData.setVisible(false);
        intens();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbMetodo = new javax.swing.JComboBox();
        lblMetodo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCons = new javax.swing.JButton();
        txtCons = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        btnCanc = new javax.swing.JButton();
        btnExc = new javax.swing.JButton();
        btnConAlt = new javax.swing.JButton();
        btnAlt = new javax.swing.JButton();
        fmtConsData = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtSobren = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        fmtxtCpf = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fmtDataCad = new javax.swing.JFormattedTextField();
        fmtxtTel = new javax.swing.JFormattedTextField();
        txtLogin = new javax.swing.JTextField();
        cmbGrupo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de Usuários"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbMetodo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbMetodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código", "Nome", "Sobrenome", "Login", "Grupo", "Data de Cadastro" }));
        cmbMetodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbMetodoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbMetodoMouseExited(evt);
            }
        });
        cmbMetodo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMetodoItemStateChanged(evt);
            }
        });
        cmbMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMetodoActionPerformed(evt);
            }
        });
        jPanel1.add(cmbMetodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 130, 30));

        lblMetodo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMetodo.setText("Código:");
        jPanel1.add(lblMetodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Método de Pesquisa:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        btnCons.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCons.setText("Consultar");
        btnCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsActionPerformed(evt);
            }
        });
        jPanel1.add(btnCons, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, 30));

        txtCons.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsActionPerformed(evt);
            }
        });
        txtCons.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MetodoPesquisa(evt);
            }
        });
        txtCons.setDocument(new UpperCaseDocument());
        jPanel1.add(txtCons, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 40, 30));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Sobrenome", "CPF", "Email", "Data de Cadastro", "Telefone", "Login", "Grupo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        tbl.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tbl);
        if (tbl.getColumnModel().getColumnCount() > 0) {
            tbl.getColumnModel().getColumn(0).setPreferredWidth(25);
            tbl.getColumnModel().getColumn(6).setPreferredWidth(45);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1100, 200));

        btnCanc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCanc.setText("Sair");
        btnCanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancActionPerformed(evt);
            }
        });
        jPanel1.add(btnCanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 380, -1, 30));

        btnExc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnExc.setText("Excluir");
        btnExc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcActionPerformed(evt);
            }
        });
        jPanel1.add(btnExc, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, -1, 30));

        btnConAlt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnConAlt.setText("Confirmar alteração");
        btnConAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConAltActionPerformed(evt);
            }
        });
        jPanel1.add(btnConAlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 160, 30));

        btnAlt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAlt.setText("Alterar");
        btnAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 160, 30));

        try {
            fmtConsData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(fmtConsData, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 80, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nome:*");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        txtNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNome.setEnabled(false);
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeApenasTexto(evt);
            }
        });
        txtNome.setDocument(new UpperCaseDocument());
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 120, 30));

        txtSobren.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtSobren.setEnabled(false);
        txtSobren.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSobrenApenasTexto(evt);
            }
        });
        txtSobren.setDocument(new UpperCaseDocument());
        jPanel1.add(txtSobren, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 120, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Sobrenome:*");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("CPF:*");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Email:*");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, -1, -1));

        txtEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtEmail.setEnabled(false);
        txtEmail.setDocument(new UpperCaseDocument());
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 380, 30));

        try {
            fmtxtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fmtxtCpf.setEnabled(false);
        jPanel1.add(fmtxtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 120, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Grupo:*");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Login:*");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Telefone:*");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Data de Cadastro:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        try {
            fmtDataCad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fmtDataCad.setEnabled(false);
        jPanel1.add(fmtDataCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 130, 30));

        try {
            fmtxtTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fmtxtTel.setEnabled(false);
        jPanel1.add(fmtxtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 130, 30));

        txtLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtLogin.setEnabled(false);
        txtLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLoginLoginSenha(evt);
            }
        });
        jPanel1.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 130, 30));

        cmbGrupo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbGrupo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "*GRUPO*" }));
        cmbGrupo.setEnabled(false);
        cmbGrupo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cmbGrupoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(cmbGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 130, 30));

        jLabel5.setText("* = campos obrigatórios");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel7.setText("* = campos obrigatórios");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1120, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void intens(){
        Pesquisa completa = new Pesquisa();

        completa.setUsuario(txtCons.getText());
        PesquisaDAO pes = new PesquisaDAO();
        pes.pesquisar(completa, txtCons);
    }
    
    public void intens2(){
        Pesquisa completa = new Pesquisa();

        completa.setUsuario(txtCons.getText());
        PesquisaDAO pes = new PesquisaDAO();
        pes.pesquisarSobrenome(completa, txtCons);
    }
    
    private void btnAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltActionPerformed
        if (!"".equals(txtNome.getText())) {
            int resposta = JOptionPane.showConfirmDialog(null, "Deseja fazer essa alteração?");
            if (resposta == 0 ) {
                txtNome.setEnabled(true);
                txtSobren.setEnabled(true);
                fmtxtCpf.setEnabled(true);
                txtEmail.setEnabled(true);
                fmtxtTel.setEnabled(true);
                txtLogin.setEnabled(true);
                cmbGrupo.setEnabled(true);
                alteracao = true;
            }
            else if (resposta == 1) {
                txtNome.setEnabled(false);
                txtSobren.setEnabled(false);
                fmtxtCpf.setEnabled(false);
                txtEmail.setEnabled(false);
                fmtxtTel.setEnabled(false);
                txtLogin.setEnabled(false);
                cmbGrupo.setEnabled(false);
                boolean alteracao = false;
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Selecione um usuário primeiro!");
        }
    }//GEN-LAST:event_btnAltActionPerformed

    private void btnConAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConAltActionPerformed
        
        try{
            if ((alteracao == true)) {
                if ((cmbGrupo.getSelectedIndex() != 0) && (!"".equals(txtNome.getText())) && (!"".equals(txtSobren.getText())) &&
                (!"   .   .   -  ".equals(fmtxtCpf.getText())) && (!"".equals(txtEmail.getText())) && (!"(  )    -    ".equals(fmtxtTel.getText())) &&
                (!"".equals(txtLogin.getText()))) {
                    String testeddd;
                    testeddd = fmtxtTel.getText().substring(1,3);
                    int testedddint = Integer.parseInt(testeddd);
                    if ((testedddint > 10) && (testedddint <= 19)) {
                        Usuario usuario = new Usuario();

                        usuario.setId_user(Integer.parseInt(txtCons.getText()));
                        usuario.setNome_user(txtNome.getText());
                        usuario.setSobrenome_user(txtSobren.getText());
                        usuario.setCpf_user(fmtxtCpf.getText());
                        usuario.setEmail_user(txtEmail.getText());
                        usuario.setLogin_user(txtLogin.getText());
                        usuario.setFk_tipo_user(cmbGrupo.getSelectedIndex());
                        usuario.setTel_user(fmtxtTel.getText());

                        txtNome.setEnabled(false);
                        txtSobren.setEnabled(false);
                        fmtxtCpf.setEnabled(false);
                        txtEmail.setEnabled(false);
                        fmtxtTel.setEnabled(false);
                        txtLogin.setEnabled(false);
                        cmbGrupo.setEnabled(false);
                        alteracao = false;
                        UsuarioDAO dao = new UsuarioDAO();
                        dao.alterar(usuario);
                        JOptionPane.showMessageDialog(null, "Dados alterados com sucesso!");
                        tblAncestorAdded(null);
                    }else{
                        JOptionPane.showMessageDialog(null, "Certifique-se de colocar um DDD válido!");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Certifique-se de não ter deixado nenhum campo em branco e selecionado um grupo válido!");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Realize uma alteração em um registro primeiro!");
                txtCons.requestFocus();
            }                         
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro não identificado: "+e);
        }
    }//GEN-LAST:event_btnConAltActionPerformed

    private void btnExcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcActionPerformed
        if ("".equals(txtNome.getText())) {
            JOptionPane.showMessageDialog(null, "Selecione um registro primeiro!");
            txtCons.requestFocus();
        }
        else
        {
            Usuario usuario = new Usuario();
            int resposta=JOptionPane.showConfirmDialog(null, "Deseja mesmo excluir?");
            if (resposta == 0) {
                usuario.setId_user(Integer.parseInt(txtCons.getText()));
                UsuarioDAO dao = new UsuarioDAO();
                dao.deletar(usuario);
                JOptionPane.showMessageDialog(null, "Registro removido com sucesso!");
                txtCons.setText("");
                txtNome.setText("");
                txtSobren.setText("");
                fmtxtCpf.setText("");
                txtEmail.setText("");
                fmtxtTel.setText("");
                txtLogin.setText("");
                fmtDataCad.setText("");
                cmbGrupo.setSelectedIndex(0);
                tblAncestorAdded(null);
                txtCons.requestFocus();
            }
        }
    }//GEN-LAST:event_btnExcActionPerformed

    private void btnCancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        if (evt.getClickCount() ==  1) {
            Usuario usuario = new Usuario();
            txtCons.setText(tbl.getValueAt(tbl.getSelectedRow(), 0).toString());
            txtNome.setText(tbl.getValueAt(tbl.getSelectedRow(), 1).toString());
            txtSobren.setText(tbl.getValueAt(tbl.getSelectedRow(), 2).toString());
            fmtxtCpf.setText(tbl.getValueAt(tbl.getSelectedRow(), 3).toString());
            txtEmail.setText(tbl.getValueAt(tbl.getSelectedRow(), 4).toString());
            fmtDataCad.setText(tbl.getValueAt(tbl.getSelectedRow(), 5).toString());
            fmtxtTel.setText(tbl.getValueAt(tbl.getSelectedRow(), 6).toString());
            txtLogin.setText(tbl.getValueAt(tbl.getSelectedRow(), 7).toString());
            cmbGrupo.setSelectedItem(tbl.getValueAt(tbl.getSelectedRow(), 8).toString());
            
            UsuarioDAO dao = new UsuarioDAO();
            usuario.setId_user(Integer.parseInt(txtCons.getText()));
            dao.pesquisar(usuario);
        }
    }//GEN-LAST:event_tblMouseClicked

    private void tblAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblAncestorAdded
        UsuarioDAO dao = new UsuarioDAO();
        List<Usuario> usuarios = dao.getLista();
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        model.setNumRows(0);
        for (Usuario usuario : usuarios) {
            model.addRow(new Object[]{
                usuario.getId_user(),
                usuario.getNome_user(),
                usuario.getSobrenome_user(),
                usuario.getCpf_user(),
                usuario.getEmail_user(),
                usuario.getData_cad(),
                usuario.getTel_user(),
                usuario.getLogin_user(),
                usuario.getFk_tipo()
            });
        }
    }//GEN-LAST:event_tblAncestorAdded

    private void MetodoPesquisa(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MetodoPesquisa
        if ("Código:".equals(lblMetodo.getText())) {
            String cons = txtCons.getText();
            int quantCaracteres = cons.length();
            if (quantCaracteres > 2){
                cons = cons.substring (0, cons.length() - 1);
                txtCons.setText(cons);
            }
            String caracteres="0123456789 ";
            if(!caracteres.contains(evt.getKeyChar()+"")){
                evt.consume();
            }         
        }
        else if (("Nome:".equals(lblMetodo.getText())) || ("Sobrenome:".equals(lblMetodo.getText()))
            || ("Login:".equals(lblMetodo.getText())) || ("Grupo:".equals(lblMetodo.getText()))) {
            String cons = txtCons.getText();
            int quantCaracteres = cons.length();
            if (quantCaracteres > 10){
                cons = cons.substring (0, cons.length() - 1);
                txtCons.setText(cons);
            }
            String caracteres="0987654321!@#$%¨&*()/\\*-+.,{}[]<>;:?°ºª'|\"=_`^~´¬§¢£³²¹°ºª ";
            if(caracteres.contains(evt.getKeyChar()+"")){
                evt.consume();
            }
        }
    }//GEN-LAST:event_MetodoPesquisa

    private void btnConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsActionPerformed
        try {
            Usuario usuario = new Usuario();
            UsuarioDAO dao = new UsuarioDAO();
            if (cmbMetodo.getSelectedItem() == "Código") {
                usuario.setId_user(Integer.parseInt(txtCons.getText()));
                dao.pesquisar(usuario);
            }
            else if (cmbMetodo.getSelectedItem() == "Nome"){
                usuario.setNome_user(txtCons.getText());
                dao.pesquisarNome(usuario);
            }
            else if (cmbMetodo.getSelectedItem() == "Sobrenome") {
                usuario.setSobrenome_user(txtCons.getText());
                
            }

            txtNome.setText(usuario.getNome_user());
            txtSobren.setText(usuario.getSobrenome_user());
            fmtxtCpf.setText(usuario.getCpf_user());
            txtEmail.setText(usuario.getEmail_user());
            fmtxtTel.setText(usuario.getTel_user());
            cmbGrupo.setSelectedIndex(usuario.getFk_tipo_user());
            fmtDataCad.setText(usuario.getData_cad());
            txtLogin.setText(usuario.getLogin_user());
            //            fmtxtTel.setText("("+String.valueOf(usuario.getFk_ddd())+")"+usuario.getTel_user());
            //            JOptionPane.showMessageDialog(null, "("+String.valueOf(usuario.getFk_ddd())+")"+usuario.getTel_user());

            if (txtNome.getText().equals("")) {
                txtCons.setText("");
                JOptionPane.showMessageDialog(null, "Usuário não cadastrado!");

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Insira um ID válido!");
            txtCons.requestFocus();
        }
    }//GEN-LAST:event_btnConsActionPerformed

    private void txtNomeApenasTexto(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeApenasTexto
        String caracteres="0123456789!@#$%¨&*()/\\*-+.,{}[]<>;:?°ºª'|\"=_`^~´¬§¢£³²¹°ºª";
        if(caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_txtNomeApenasTexto

    private void txtSobrenApenasTexto(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSobrenApenasTexto
        String caracteres="0123456789!@#$%¨&*()/\\*-+.,{}[]<>;:?°ºª'|\"=_`^~´¬§¢£³²¹°ºª";
        if(caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_txtSobrenApenasTexto

    private void txtLoginLoginSenha(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginLoginSenha
        String caracteres="!@#$%¨&*()/\\*-+.,{}[]<>;:?°ºª'|\"=_`^~´¬§¢£³²¹°ºª ";
        if(caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_txtLoginLoginSenha

    private void cmbGrupoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cmbGrupoAncestorAdded
        TipousuarioDAO dao = new TipousuarioDAO();
        List<Tipousuario> tipo_usuarios = dao.getLista();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cmbGrupo.getModel();
        for (Tipousuario tipo_usuario : tipo_usuarios) {
            model.addElement(tipo_usuario.getTipo_user());
        }
    }//GEN-LAST:event_cmbGrupoAncestorAdded

    private void cmbMetodoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMetodoItemStateChanged
//        switch(cmbMetodo.getSelectedIndex()){
//            case 0:
//                txtCons.setVisible(true);
//                txtCons.setSize(40, 30);
//                btnCons.setLocation(360, 30);
//                lblMetodo.setText("Código:");
//                fmtConsData.setVisible(false);
//                break;
//            case 1:
//                txtCons.setVisible(true);
//                txtCons.setSize(110, 30);  
//                btnCons.setLocation(410, 30);
//                lblMetodo.setText("Nome:");
//                fmtConsData.setVisible(false);
//                break;
//            case 2:
//                lblMetodo.setText("Sobrenome:");
//                btnCons.setLocation(410, 30);
//                txtCons.setSize(110, 30);
//                lblMetodo.setLocation(180, 40); 
//                break;
//            case 3:
//                lblMetodo.setText("Login:");
//                fmtConsData.setVisible(false);
//                txtCons.setVisible(true);
//                txtCons.setSize(110, 30);
//                btnCons.setLocation(410, 30);
//                break;
//            case 4:
//                lblMetodo.setText("Grupo:");
//                fmtConsData.setVisible(false);
//                txtCons.setVisible(true);
//                txtCons.setSize(110, 30);
//                btnCons.setLocation(410, 30);
//                break;
//            case 5:
//                lblMetodo.setText("Data de Entrada:");
//                fmtConsData.setLocation(330, 30);
//                btnCons.setLocation(440, 30);
//                txtCons.setVisible(false);
//                fmtConsData.setVisible(true);
//                break;
//        }
        
        
//        if (cmbMetodo.getSelectedIndex() == 0) {
//            txtCons.setVisible(true);
//            txtCons.setSize(40, 30);
//            btnCons.setLocation(360, 30);
//            lblMetodo.setText("Código:");
//            fmtConsData.setVisible(false);
//        }
//        else if (cmbMetodo.getSelectedIndex() == 1) {
//            lblMetodo.setText("Nome:");
//            btnCons.setLocation(410, 30);
//            txtCons.setSize(110, 30);
//            txtCons.setVisible(true);
//            fmtConsData.setVisible(false);
//        }
//        else if (cmbMetodo.getSelectedIndex() == 2) {
//            lblMetodo.setText("Sobrenome:");
//            btnCons.setLocation(410, 30);
//            txtCons.setSize(110, 30);
//            lblMetodo.setLocation(180, 40);       
//        }
//        else if (cmbMetodo.getSelectedIndex() == 3) {
//            lblMetodo.setText("Login:");
//            fmtConsData.setVisible(false);
//            txtCons.setVisible(true);
//            txtCons.setSize(110, 30);
//            btnCons.setLocation(410, 30);
//        }
//        else if (cmbMetodo.getSelectedIndex() == 4) {
//            lblMetodo.setText("Grupo:");
//            fmtConsData.setVisible(false);
//            txtCons.setVisible(true);
//            txtCons.setSize(110, 30);
//            btnCons.setLocation(410, 30);
//        }
//        else if (cmbMetodo.getSelectedIndex() == 5) {
//            lblMetodo.setText("Data de Entrada:");
//            fmtConsData.setLocation(330, 30);
//            btnCons.setLocation(440, 30);
//            txtCons.setVisible(false);
//            fmtConsData.setVisible(true);
//        }
    }//GEN-LAST:event_cmbMetodoItemStateChanged

    private void cmbMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMetodoActionPerformed
//        switch(cmbMetodo.getSelectedIndex()){
//            case 0:
//                txtCons.setVisible(true);
//                txtCons.setSize(40, 30);
//                btnCons.setLocation(360, 30);
//                lblMetodo.setText("Código:");
//                fmtConsData.setVisible(false);
//                break;
//            case 1:
//                lblMetodo.setText("Nome:");
//                btnCons.setLocation(410, 30);
//                txtCons.setSize(110, 30);
//                txtCons.setVisible(true);
//                fmtConsData.setVisible(false);
//                break;
//            case 2:
//                lblMetodo.setText("Sobrenome:");
//                btnCons.setLocation(410, 30);
//                txtCons.setSize(110, 30);
//                lblMetodo.setLocation(180, 40); 
//                break;
//            case 3:
//                lblMetodo.setText("Login:");
//                fmtConsData.setVisible(false);
//                txtCons.setVisible(true);
//                txtCons.setSize(110, 30);
//                btnCons.setLocation(410, 30);
//                break;
//            case 4:
//                lblMetodo.setText("Grupo:");
//                fmtConsData.setVisible(false);
//                txtCons.setVisible(true);
//                txtCons.setSize(110, 30);
//                btnCons.setLocation(410, 30);
//                break;
//            case 5:
//                lblMetodo.setText("Data de Entrada:");
//                fmtConsData.setLocation(330, 30);
//                btnCons.setLocation(440, 30);
//                txtCons.setVisible(false);
//                fmtConsData.setVisible(true);
//                break;
//        }


//        if (cmbMetodo.getSelectedIndex() == 0) {
//            txtCons.setVisible(true);
//            txtCons.setSize(40, 30);
//            btnCons.setLocation(360, 30);
//            lblMetodo.setText("Código:");
//            fmtConsData.setVisible(false);
//        }
//        else if (cmbMetodo.getSelectedIndex() == 1) {
//            lblMetodo.setText("Nome:");
//            btnCons.setLocation(410, 30);
//            txtCons.setSize(110, 30);
//            txtCons.setVisible(true);
//            fmtConsData.setVisible(false);
//        }
//        else if (cmbMetodo.getSelectedIndex() == 2) {
//            lblMetodo.setText("Sobrenome:");
//            btnCons.setLocation(410, 30);
//            txtCons.setSize(110, 30);
//            lblMetodo.setLocation(180, 40);
//            txtCons.setVisible(true);
//            fmtConsData.setVisible(false);          
//        }
//        else if (cmbMetodo.getSelectedIndex() == 3) {
//            lblMetodo.setText("Login:");
//            fmtConsData.setVisible(false);
//            txtCons.setVisible(true);
//            txtCons.setSize(110, 30);
//            btnCons.setLocation(410, 30);
//        }
//        else if (cmbMetodo.getSelectedIndex() == 4) {
//            lblMetodo.setText("Grupo:");
//            fmtConsData.setVisible(false);
//            txtCons.setVisible(true);
//            txtCons.setSize(110, 30);
//            btnCons.setLocation(410, 30);
//        }
//        else if (cmbMetodo.getSelectedIndex() == 5) {
//            lblMetodo.setText("Data de Entrada:");
//            fmtConsData.setLocation(330, 30);
//            btnCons.setLocation(440, 30);
//            txtCons.setVisible(false);
//            fmtConsData.setVisible(true);
//        }
    }//GEN-LAST:event_cmbMetodoActionPerformed

    private void cmbMetodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbMetodoMouseClicked
//        if (cmbMetodo.getSelectedIndex() == 0) {
//            txtCons.setVisible(true);
//            txtCons.setSize(40, 30);
//            btnCons.setLocation(360, 30);
//            lblMetodo.setText("Código:");
//            fmtConsData.setVisible(false);
//        }
//        else if (cmbMetodo.getSelectedIndex() == 1) {
//            lblMetodo.setText("Nome:");
//            btnCons.setLocation(410, 30);
//            txtCons.setSize(110, 30);
//            txtCons.setVisible(true);
//            fmtConsData.setVisible(false);
//        }
//        else if (cmbMetodo.getSelectedIndex() == 2) {
//            lblMetodo.setText("Sobrenome:");
//            btnCons.setLocation(410, 30);
//            txtCons.setSize(110, 30);
//            lblMetodo.setLocation(180, 40);
//            txtCons.setVisible(true);
//            fmtConsData.setVisible(false);          
//        }
//        else if (cmbMetodo.getSelectedIndex() == 3) {
//            lblMetodo.setText("Login:");
//            fmtConsData.setVisible(false);
//            txtCons.setVisible(true);
//            txtCons.setSize(110, 30);
//            btnCons.setLocation(410, 30);
//        }
//        else if (cmbMetodo.getSelectedIndex() == 4) {
//            lblMetodo.setText("Grupo:");
//            fmtConsData.setVisible(false);
//            txtCons.setVisible(true);
//            txtCons.setSize(110, 30);
//            btnCons.setLocation(410, 30);
//        }
//        else if (cmbMetodo.getSelectedIndex() == 5) {
//            lblMetodo.setText("Data de Entrada:");
//            fmtConsData.setLocation(330, 30);
//            btnCons.setLocation(440, 30);
//            txtCons.setVisible(false);
//            fmtConsData.setVisible(true);
//        }
    }//GEN-LAST:event_cmbMetodoMouseClicked

    private void cmbMetodoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbMetodoMouseExited
//        if (cmbMetodo.getSelectedIndex() == 0) {
//            txtCons.setVisible(true);
//            txtCons.setSize(40, 30);
//            btnCons.setLocation(360, 30);
//            lblMetodo.setText("Código:");
//            fmtConsData.setVisible(false);
//        }
//        else if (cmbMetodo.getSelectedIndex() == 1) {
//            lblMetodo.setText("Nome:");
//            btnCons.setLocation(410, 30);
//            txtCons.setSize(110, 30);
//            txtCons.setVisible(true);
//            fmtConsData.setVisible(false);
//        }
//        else if (cmbMetodo.getSelectedIndex() == 2) {
//            lblMetodo.setText("Sobrenome:");
//            btnCons.setLocation(410, 30);
//            txtCons.setSize(110, 30);
//            lblMetodo.setLocation(180, 40);
//            txtCons.setVisible(true);
//            fmtConsData.setVisible(false);          
//        }
//        else if (cmbMetodo.getSelectedIndex() == 3) {
//            lblMetodo.setText("Login:");
//            fmtConsData.setVisible(false);
//            txtCons.setVisible(true);
//            txtCons.setSize(110, 30);
//            btnCons.setLocation(410, 30);
//        }
//        else if (cmbMetodo.getSelectedIndex() == 4) {
//            lblMetodo.setText("Grupo:");
//            fmtConsData.setVisible(false);
//            txtCons.setVisible(true);
//            txtCons.setSize(110, 30);
//            btnCons.setLocation(410, 30);
//        }
//        else if (cmbMetodo.getSelectedIndex() == 5) {
//            lblMetodo.setText("Data de Entrada:");
//            fmtConsData.setLocation(330, 30);
//            btnCons.setLocation(440, 30);
//            txtCons.setVisible(false);
//            fmtConsData.setVisible(true);
//        }
    }//GEN-LAST:event_cmbMetodoMouseExited

    private void txtConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsActionPerformed
        btnConsActionPerformed(null);
    }//GEN-LAST:event_txtConsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlt;
    private javax.swing.JButton btnCanc;
    private javax.swing.JButton btnConAlt;
    private javax.swing.JButton btnCons;
    private javax.swing.JButton btnExc;
    private javax.swing.JComboBox cmbGrupo;
    private javax.swing.JComboBox cmbMetodo;
    private javax.swing.JFormattedTextField fmtConsData;
    private javax.swing.JFormattedTextField fmtDataCad;
    private javax.swing.JFormattedTextField fmtxtCpf;
    private javax.swing.JFormattedTextField fmtxtTel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMetodo;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtCons;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSobren;
    // End of variables declaration//GEN-END:variables
}