/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.technobsoftwares.gpiec.formulario;

import br.com.technobsoftwares.gpiec.dao.TipousuarioDAO;
import br.com.technobsoftwares.gpiec.dao.UsuarioDAO;
import br.com.technobsoftwares.gpiec.modelo.Tipousuario;
import br.com.technobsoftwares.gpiec.modelo.Usuario;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Henrique C
 */
public class FrmInCadUser extends javax.swing.JInternalFrame {
    public static String nome_grupo;
    //public static String nometipouser;
    /**
     * Creates new form FrmCadUser
     */
    public FrmInCadUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtSobren = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        psrSenha = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fmtxtCpf = new javax.swing.JFormattedTextField();
        txtEmail = new javax.swing.JTextField();
        cmbTipoUser = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        psrConSenha = new javax.swing.JPasswordField();
        txtLogin = new javax.swing.JTextField();
        fmtxtTel = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Usuários"));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TeclaPressionada(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Nome:*");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        txtNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TeclaPressionada(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeApenasTexto(evt);
            }
        });
        txtNome.setDocument(new UpperCaseDocument());
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 150, 30));

        txtSobren.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtSobren.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TeclaPressionada(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSobrenApenasTexto(evt);
            }
        });
        txtSobren.setDocument(new UpperCaseDocument());
        jPanel1.add(txtSobren, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 150, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Sobrenome:*");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        psrSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        psrSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TeclaPressionada(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                psrSenhaFormatTextNumber(evt);
            }
        });
        jPanel1.add(psrSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 150, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Senha:*");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Email:*");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("CPF:*");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        try {
            fmtxtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fmtxtCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TeclaPressionada(evt);
            }
        });
        jPanel1.add(fmtxtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 120, 30));

        txtEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TeclaPressionada(evt);
            }
        });
        txtEmail.setDocument(new UpperCaseDocument());
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 470, 30));

        cmbTipoUser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbTipoUser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "*GRUPOS*" }));
        cmbTipoUser.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoUserItemStateChanged(evt);
            }
        });
        cmbTipoUser.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cmbTipoUserAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cmbTipoUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TeclaPressionada(evt);
            }
        });
        jPanel1.add(cmbTipoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 130, 30));

        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TeclaPressionada(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, -1, 30));

        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TeclaPressionada(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, -1, 30));

        btnCadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        btnCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TeclaPressionada(evt);
            }
        });
        jPanel1.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, 30));

        psrConSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        psrConSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TeclaPressionada(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                psrConSenhapsrSenhaFormatTextNumber(evt);
            }
        });
        jPanel1.add(psrConSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 150, 30));

        txtLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TeclaPressionada(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLoginFormatTextNumber(evt);
            }
        });
        jPanel1.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 150, 30));

        try {
            fmtxtTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fmtxtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TeclaPressionada(evt);
            }
        });
        jPanel1.add(fmtxtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 150, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Telefone:*");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Login:*");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Confirmar senha:*");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Grupos:*");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        jLabel5.setText("* = campos obrigatórios");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 620, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeApenasTexto(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeApenasTexto
        String caracteres="0987654321!@#$%¨&*()/\\*-+.,{}[]<>;:?°ºª'|\"=_`^~´¬§¢£³²¹°ºª";
        if(caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_txtNomeApenasTexto

    private void txtSobrenApenasTexto(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSobrenApenasTexto
        String caracteres="0987654321!@#$%¨&*()/\\*-+.,{}[]<>;:?°ºª'|\"=_`^~´¬§¢£³²¹°ºª";
        if(caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_txtSobrenApenasTexto

    private void psrSenhaFormatTextNumber(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_psrSenhaFormatTextNumber
        String caracteres="!@#$%¨&*()/\\*-+.,{}[]<>;:?°ºª'|\"=_`^~´¬§¢£³²¹°ºª ";
        if(caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_psrSenhaFormatTextNumber

    private void cmbTipoUserAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cmbTipoUserAncestorAdded
        TipousuarioDAO dao = new TipousuarioDAO();
        List<Tipousuario> tipo_usuarios = dao.getLista();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cmbTipoUser.getModel();
        for (Tipousuario tipo_usuario : tipo_usuarios) {
            model.addElement(tipo_usuario.getTipo_user());
        }
    }//GEN-LAST:event_cmbTipoUserAncestorAdded

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtNome.setText("");
        txtSobren.setText("");
        fmtxtCpf.setText("");
        txtEmail.setText("");
        psrConSenha.setText("");
        fmtxtTel.setText("");
        txtLogin.setText("");
        psrSenha.setText("");
        cmbTipoUser.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if ((!"".equals(txtNome.getText())) && (!"".equals(txtSobren.getText())) &&
            (!"   .   .   -  ".equals(fmtxtCpf.getText())) && (!"".equals(txtEmail.getText())) &&
            (psrConSenha.getText().equals(psrSenha.getText())) && (!"(  )    -    ".equals(fmtxtTel.getText())) &&
            (!"".equals(txtLogin.getText())) && (!"".equals(psrSenha.getText())) &&
            (cmbTipoUser.getSelectedIndex() != 0)) {
            
            String testeddd = fmtxtTel.getText().substring(1,3);        
            int teste = Integer.parseInt(testeddd);

            try{
                if ((teste > 10) && (teste <= 19)) {

                    Usuario usuario = new Usuario();               

                    usuario.setNome_user(txtNome.getText());
                    usuario.setSobrenome_user(txtSobren.getText());
                    usuario.setCpf_user(fmtxtCpf.getText());
                    usuario.setEmail_user(txtEmail.getText());
                    usuario.setTel_user(fmtxtTel.getText());
                    TipousuarioDAO tuser = new TipousuarioDAO();
                    usuario.setFk_tipo_user(tuser.teste_id_grupos);
                    usuario.setLogin_user(txtLogin.getText());
                    usuario.setSenha_user(psrSenha.getText());

                    UsuarioDAO dao = new UsuarioDAO();
                    dao.adiciona(usuario);

                    JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
                    txtNome.setText("");
                    txtSobren.setText("");
                    fmtxtCpf.setText("");
                    txtEmail.setText("");
                    psrConSenha.setText("");
                    fmtxtTel.setText("");
                    txtLogin.setText("");
                    psrSenha.setText("");
                    cmbTipoUser.setSelectedIndex(0);
                    txtNome.requestFocus();
                } else{
                    JOptionPane.showMessageDialog(null, "Insira um DDD válido!");
                    txtNome.requestFocus();
                }
            } catch (Exception e) {
                txtNome.setText("");
                txtSobren.setText("");
                fmtxtCpf.setText("");
                txtEmail.setText("");
                psrConSenha.setText("");
                fmtxtTel.setText("");
                txtLogin.setText("");
                psrSenha.setText("");
                cmbTipoUser.setSelectedIndex(0);
                txtNome.requestFocus();
                JOptionPane.showMessageDialog(null, "Usuário já cadastrado!");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Preencha todos os campos e selecione um grupo de usuário!");
        }                
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void psrConSenhapsrSenhaFormatTextNumber(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_psrConSenhapsrSenhaFormatTextNumber
        String caracteres="!@#$%¨&*()/\\*-+.,{}[]<>;:?°ºª'|\"=_`^~´¬§¢£³²¹°ºª ";
        if(caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_psrConSenhapsrSenhaFormatTextNumber

    private void txtLoginFormatTextNumber(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginFormatTextNumber
        String caracteres="!@#$%¨&*()/\\*-+.,{}[]<>;:?°ºª'|\"=_`^~´¬§¢£³²¹°ºª ";
        if(caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_txtLoginFormatTextNumber

    private void cmbTipoUserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoUserItemStateChanged
        nome_grupo = String.valueOf(cmbTipoUser.getSelectedItem());
        TipousuarioDAO dao = new TipousuarioDAO();
        Tipousuario tuser = new Tipousuario();
        dao.pesquisa_grupo(tuser);
    }//GEN-LAST:event_cmbTipoUserItemStateChanged

    private void TeclaPressionada(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TeclaPressionada
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnCadastrarActionPerformed(null);
        }
    }//GEN-LAST:event_TeclaPressionada

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        btnCadastrarActionPerformed(null);
    }//GEN-LAST:event_txtNomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JComboBox cmbTipoUser;
    private javax.swing.JFormattedTextField fmtxtCpf;
    private javax.swing.JFormattedTextField fmtxtTel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField psrConSenha;
    private javax.swing.JPasswordField psrSenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSobren;
    // End of variables declaration//GEN-END:variables
}