/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.technobsoftwares.gpiec.formulario;

import br.com.technobsoftwares.gpiec.dao.TipousuarioDAO;
import br.com.technobsoftwares.gpiec.modelo.Tipousuario;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lab
 */
public class FrmInConsTipoUser extends javax.swing.JInternalFrame {
    int alterar = 0;
    /**
     * Creates new form FrmInRelatGrupo
     */
    public FrmInConsTipoUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        chcCadUser = new javax.swing.JCheckBox();
        chcConsUser = new javax.swing.JCheckBox();
        chcEditUser = new javax.swing.JCheckBox();
        chcEditOS = new javax.swing.JCheckBox();
        chcAbrirOS = new javax.swing.JCheckBox();
        chcFecharOS = new javax.swing.JCheckBox();
        chcRelatOS = new javax.swing.JCheckBox();
        chcEditGrupo = new javax.swing.JCheckBox();
        chcEditPatr = new javax.swing.JCheckBox();
        chcEditLocal = new javax.swing.JCheckBox();
        chcEditSoft = new javax.swing.JCheckBox();
        chcEditHard = new javax.swing.JCheckBox();
        chcConsGrupo = new javax.swing.JCheckBox();
        chcConsPatr = new javax.swing.JCheckBox();
        chcConsLocal = new javax.swing.JCheckBox();
        chcConsSoft = new javax.swing.JCheckBox();
        chcConsHard = new javax.swing.JCheckBox();
        chcCadGrupo = new javax.swing.JCheckBox();
        chcCadPatr = new javax.swing.JCheckBox();
        chcCadLocal = new javax.swing.JCheckBox();
        chcCadSoft = new javax.swing.JCheckBox();
        chcCadHard = new javax.swing.JCheckBox();
        chcTodas = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        txtCons = new javax.swing.JTextField();
        btnCons = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cmbMetod = new javax.swing.JComboBox();
        txtNomeGrupo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        btnConAlt = new javax.swing.JButton();
        btnAlt = new javax.swing.JButton();
        btnCanc = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de Grupos"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Permissões de Grupo"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chcCadUser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chcCadUser.setText("Cadastrar Usuários");
        chcCadUser.setEnabled(false);
        jPanel2.add(chcCadUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 30));

        chcConsUser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chcConsUser.setText("Consultar Usuários");
        chcConsUser.setEnabled(false);
        jPanel2.add(chcConsUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, 30));

        chcEditUser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chcEditUser.setText("Relatório Dados de Usuários");
        chcEditUser.setEnabled(false);
        jPanel2.add(chcEditUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, 30));

        chcEditOS.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chcEditOS.setText("Gerenciar O.S");
        chcEditOS.setEnabled(false);
        jPanel2.add(chcEditOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, -1, 30));

        chcAbrirOS.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chcAbrirOS.setText("Abrir O.S");
        chcAbrirOS.setEnabled(false);
        jPanel2.add(chcAbrirOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, -1, 30));

        chcFecharOS.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chcFecharOS.setText("Fechar O.S ");
        chcFecharOS.setEnabled(false);
        jPanel2.add(chcFecharOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, -1, 30));

        chcRelatOS.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chcRelatOS.setText("Relatório de O.S");
        chcRelatOS.setEnabled(false);
        jPanel2.add(chcRelatOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, -1, 30));

        chcEditGrupo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chcEditGrupo.setText("Relatório Dados de Grupos");
        chcEditGrupo.setEnabled(false);
        jPanel2.add(chcEditGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, 30));

        chcEditPatr.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chcEditPatr.setText("Relatório Dados de Patrimônios");
        chcEditPatr.setEnabled(false);
        jPanel2.add(chcEditPatr, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, 30));

        chcEditLocal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chcEditLocal.setText("Relatório Dados de Locais");
        chcEditLocal.setEnabled(false);
        jPanel2.add(chcEditLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, 30));

        chcEditSoft.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chcEditSoft.setText("Relatório Dados de Softwares");
        chcEditSoft.setEnabled(false);
        jPanel2.add(chcEditSoft, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, 30));

        chcEditHard.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chcEditHard.setText("Relatório Dados de Hardwares");
        chcEditHard.setEnabled(false);
        jPanel2.add(chcEditHard, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, 30));

        chcConsGrupo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chcConsGrupo.setText("Consultar Grupos");
        chcConsGrupo.setEnabled(false);
        jPanel2.add(chcConsGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, 30));

        chcConsPatr.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chcConsPatr.setText("Consultar Patrimônios");
        chcConsPatr.setEnabled(false);
        jPanel2.add(chcConsPatr, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, 30));

        chcConsLocal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chcConsLocal.setText("Consultar Locais");
        chcConsLocal.setEnabled(false);
        jPanel2.add(chcConsLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, 30));

        chcConsSoft.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chcConsSoft.setText("Consultar Software");
        chcConsSoft.setEnabled(false);
        jPanel2.add(chcConsSoft, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, 30));

        chcConsHard.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chcConsHard.setText("Consultar Hardware");
        chcConsHard.setEnabled(false);
        jPanel2.add(chcConsHard, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, 30));

        chcCadGrupo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chcCadGrupo.setText("Cadastrar Grupos");
        chcCadGrupo.setEnabled(false);
        jPanel2.add(chcCadGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 30));

        chcCadPatr.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chcCadPatr.setText("Cadastrar Patrimônios");
        chcCadPatr.setEnabled(false);
        jPanel2.add(chcCadPatr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));

        chcCadLocal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chcCadLocal.setText("Cadastrar Local");
        chcCadLocal.setEnabled(false);
        jPanel2.add(chcCadLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 30));

        chcCadSoft.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chcCadSoft.setText("Cadastrar Software");
        chcCadSoft.setEnabled(false);
        jPanel2.add(chcCadSoft, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 30));

        chcCadHard.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chcCadHard.setText("Cadastrar Hardware");
        chcCadHard.setEnabled(false);
        jPanel2.add(chcCadHard, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 30));

        chcTodas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chcTodas.setText("Marcar/Desmarcar Todas");
        chcTodas.setEnabled(false);
        chcTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chcTodasActionPerformed(evt);
            }
        });
        jPanel2.add(chcTodas, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 179, 990, 280));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Código:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        txtCons.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsActionPerformed(evt);
            }
        });
        jPanel1.add(txtCons, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 40, 30));

        btnCons.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCons.setText("Consultar");
        btnCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsActionPerformed(evt);
            }
        });
        jPanel1.add(btnCons, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Método de Pesquisa:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, -1, -1));

        cmbMetod.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbMetod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código", "Status", "Data de Entrada", "Tipo", "Local" }));
        jPanel1.add(cmbMetod, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, -1, 30));

        txtNomeGrupo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNomeGrupo.setEnabled(false);
        txtNomeGrupo.setDocument(new UpperCaseDocument());
        txtNomeGrupo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeGrupoKeyTyped(evt);
            }
        });
        jPanel1.add(txtNomeGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 147, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nome do Grupo:*");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Grupo", "Quantidade de Usuários"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tbl);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 1000, 200));

        btnConAlt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnConAlt.setText("Confirmar alteração");
        btnConAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConAltActionPerformed(evt);
            }
        });
        jPanel1.add(btnConAlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, 160, 30));

        btnAlt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAlt.setText("Alterar");
        btnAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 160, 30));

        btnCanc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCanc.setText("Sair");
        btnCanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancActionPerformed(evt);
            }
        });
        jPanel1.add(btnCanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 550, -1, 30));

        btnDeletar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDeletar.setText("Excluir");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 523, -1, 30));

        jLabel7.setText("* = campos obrigatórios");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 820, 190, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1020, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancActionPerformed

    private void btnConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsActionPerformed
        if ("".equals(txtCons.getText())) {
            JOptionPane.showMessageDialog(null, "Selecione um registro primeiro!");
            txtCons.requestFocus();
        }
        else{
            try {
            Tipousuario tusuario = new Tipousuario();
            TipousuarioDAO dao = new TipousuarioDAO();
            tusuario.setId_tipouser(Integer.parseInt(txtCons.getText()));
            dao.pesquisar(tusuario);
        
            txtNomeGrupo.setText(tusuario.getTipo_user());
            chcCadUser.setSelected(tusuario.isCad_user());
            chcCadGrupo.setSelected(tusuario.isCad_grupo());
            chcCadPatr.setSelected(tusuario.isCad_patrimonio());
            chcCadLocal.setSelected(tusuario.isCad_local());
            chcCadSoft.setSelected(tusuario.isCad_soft());
            chcCadHard.setSelected(tusuario.isCad_hard());
            chcConsUser.setSelected(tusuario.isCons_user());
            chcConsGrupo.setSelected(tusuario.isCons_grupo());
            chcConsPatr.setSelected(tusuario.isCons_patrimonio());
            chcConsLocal.setSelected(tusuario.isCons_local());
            chcConsSoft.setSelected(tusuario.isCons_soft());
            chcConsHard.setSelected(tusuario.isCons_hard());
            chcEditUser.setSelected(tusuario.isEdit_user());
            chcEditGrupo.setSelected(tusuario.isEdit_grupo());
            chcEditPatr.setSelected(tusuario.isEdit_patrimonio());
            chcEditLocal.setSelected(tusuario.isEdit_local());
            chcEditSoft.setSelected(tusuario.isEdit_soft());
            chcEditHard.setSelected(tusuario.isEdit_hard());  
            chcAbrirOS.setSelected(tusuario.isAbrir_os());
            chcFecharOS.setSelected(tusuario.isFechar_os());
            chcEditOS.setSelected(tusuario.isEdit_os());
            chcRelatOS.setSelected(tusuario.isRelat_os());
            
            if (txtNomeGrupo.getText().equals("")) {
                txtCons.setText("");
                JOptionPane.showMessageDialog(null, "Grupo não cadastrado!");
            }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Insira um ID válido!");
            } 
            alterar = 1;
        }
    }//GEN-LAST:event_btnConsActionPerformed

    private void btnAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltActionPerformed
        if (alterar == 1) {
            int resposta=JOptionPane.showConfirmDialog(null, "Deseja mesmo alterar?");
            if (resposta == 0) {
                
                chcCadGrupo.setEnabled(true);
                chcCadHard.setEnabled(true);
                chcCadLocal.setEnabled(true);
                chcCadPatr.setEnabled(true);
                chcCadSoft.setEnabled(true);
                chcCadUser.setEnabled(true);
                chcConsGrupo.setEnabled(true);
                chcConsHard.setEnabled(true);
                chcConsLocal.setEnabled(true);
                chcConsPatr.setEnabled(true);
                chcConsSoft.setEnabled(true);
                chcConsUser.setEnabled(true);
                chcEditGrupo.setEnabled(true);
                chcEditHard.setEnabled(true);
                chcEditLocal.setEnabled(true);
                chcEditPatr.setEnabled(true);
                chcEditSoft.setEnabled(true);
                chcEditUser.setEnabled(true);
                chcAbrirOS.setEnabled(true);
                chcFecharOS.setEnabled(true);
                chcEditOS.setEnabled(true);
                chcRelatOS.setEnabled(true);
                chcTodas.setEnabled(true);
                txtNomeGrupo.setEnabled(true);
                
                alterar = 2;
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um registro primeiro!");
        }
    }//GEN-LAST:event_btnAltActionPerformed

    private void btnConAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConAltActionPerformed
        if (alterar == 2) {     
            if (!"".equals(txtNomeGrupo.getText())) {
                Tipousuario tipo_usuario = new Tipousuario();

                tipo_usuario.setId_tipouser(Integer.parseInt(txtCons.getText()));
                tipo_usuario.setTipo_user(txtNomeGrupo.getText());               
                tipo_usuario.setCad_user(chcCadUser.isSelected());
                tipo_usuario.setCad_grupo(chcCadGrupo.isSelected());
                tipo_usuario.setCad_patrimonio(chcCadPatr.isSelected());
                tipo_usuario.setCad_local(chcCadLocal.isSelected());
                tipo_usuario.setCad_soft(chcCadSoft.isSelected());
                tipo_usuario.setCad_hard(chcCadHard.isSelected());              
                tipo_usuario.setCons_user(chcConsUser.isSelected());
                tipo_usuario.setCons_grupo(chcConsGrupo.isSelected());
                tipo_usuario.setCons_patrimonio(chcConsPatr.isSelected());
                tipo_usuario.setCons_local(chcConsLocal.isSelected());
                tipo_usuario.setCons_soft(chcConsSoft.isSelected());
                tipo_usuario.setCons_hard(chcConsHard.isSelected());           
                tipo_usuario.setEdit_user(chcEditUser.isSelected());
                tipo_usuario.setEdit_grupo(chcEditGrupo.isSelected());
                tipo_usuario.setEdit_patrimonio(chcEditPatr.isSelected());
                tipo_usuario.setEdit_local(chcEditLocal.isSelected());
                tipo_usuario.setEdit_soft(chcEditSoft.isSelected());
                tipo_usuario.setEdit_hard(chcEditHard.isSelected());           
                tipo_usuario.setAbrir_os(chcAbrirOS.isSelected());
                tipo_usuario.setFechar_os(chcFecharOS.isSelected());
                tipo_usuario.setEdit_os(chcEditOS.isSelected());
                tipo_usuario.setRelat_os(chcRelatOS.isSelected());

                chcCadGrupo.setEnabled(false);
                chcCadHard.setEnabled(false);
                chcCadLocal.setEnabled(false);
                chcCadPatr.setEnabled(false);
                chcCadSoft.setEnabled(false);
                chcCadUser.setEnabled(false);
                chcConsGrupo.setEnabled(false);
                chcConsHard.setEnabled(false);
                chcConsLocal.setEnabled(false);
                chcConsPatr.setEnabled(false);
                chcConsSoft.setEnabled(false);
                chcConsUser.setEnabled(false);
                chcEditGrupo.setEnabled(false);
                chcEditHard.setEnabled(false);
                chcEditLocal.setEnabled(false);
                chcEditPatr.setEnabled(false);
                chcEditSoft.setEnabled(false);
                chcEditUser.setEnabled(false);
                chcAbrirOS.setEnabled(false);
                chcFecharOS.setEnabled(false);
                chcEditOS.setEnabled(false);
                chcRelatOS.setEnabled(false);
                chcTodas.setEnabled(false);
                txtNomeGrupo.setEnabled(false);

                limpar();

                txtCons.setText("");
                txtNomeGrupo.setText("");
                alterar = 0;

                TipousuarioDAO dao = new TipousuarioDAO();
                dao.alterar(tipo_usuario);

                JOptionPane.showMessageDialog(null, "Dados alterados com sucesso!");
                tblAncestorAdded(null);
                txtCons.requestFocus();
            }else{
                JOptionPane.showMessageDialog(null, "Preencha o campo \"Nome do Grupo\"!");
            }            
        }
        else{
            JOptionPane.showMessageDialog(null, "Altere um registro primeiro!");
        }
    }//GEN-LAST:event_btnConAltActionPerformed

    private void tblAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblAncestorAdded
        TipousuarioDAO dao = new TipousuarioDAO();
        List<Tipousuario> tipo_usuarios = dao.getLista();
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        model.setNumRows(0);
        for (Tipousuario tipo_usuario : tipo_usuarios) {
            model.addRow(new Object[]{
                tipo_usuario.getId_tipouser(),
                tipo_usuario.getTipo_user(),
                tipo_usuario.getQtduser()
            });
        }
    }//GEN-LAST:event_tblAncestorAdded

    private void chcTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chcTodasActionPerformed
        if (chcTodas.isSelected()) {
            chcCadGrupo.setSelected(true);
            chcCadHard.setSelected(true);
            chcCadLocal.setSelected(true);
            chcCadPatr.setSelected(true);
            chcCadSoft.setSelected(true);
            chcCadUser.setSelected(true);

            chcConsGrupo.setSelected(true);
            chcConsHard.setSelected(true);
            chcConsLocal.setSelected(true);
            chcConsPatr.setSelected(true);
            chcConsSoft.setSelected(true);
            chcConsUser.setSelected(true);

            chcEditGrupo.setSelected(true);
            chcEditHard.setSelected(true);
            chcEditLocal.setSelected(true);
            chcEditPatr.setSelected(true);
            chcEditSoft.setSelected(true);
            chcEditUser.setSelected(true);

            chcAbrirOS.setSelected(true);
            chcFecharOS.setSelected(true);
            chcEditOS.setSelected(true);
            chcRelatOS.setSelected(true);
        } else {
            limpar();
        }
    }//GEN-LAST:event_chcTodasActionPerformed

    private void limpar(){
        chcCadGrupo.setSelected(false);
        chcCadHard.setSelected(false);
        chcCadLocal.setSelected(false);
        chcCadPatr.setSelected(false);
        chcCadSoft.setSelected(false);
        chcCadUser.setSelected(false);

        chcConsGrupo.setSelected(false);
        chcConsHard.setSelected(false);
        chcConsLocal.setSelected(false);
        chcConsPatr.setSelected(false);
        chcConsSoft.setSelected(false);
        chcConsUser.setSelected(false);

        chcEditGrupo.setSelected(false);
        chcEditHard.setSelected(false);
        chcEditLocal.setSelected(false);
        chcEditPatr.setSelected(false);
        chcEditSoft.setSelected(false);
        chcEditUser.setSelected(false);

        chcAbrirOS.setSelected(false);
        chcFecharOS.setSelected(false);
        chcEditOS.setSelected(false);
        chcRelatOS.setSelected(false);
    }
    
    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        if ("".equals(txtNomeGrupo.getText())) {
            JOptionPane.showMessageDialog(null, "Selecione um registro primeiro!");
        }
        else
        {
            Tipousuario tusuario = new Tipousuario();
            int resposta=JOptionPane.showConfirmDialog(null, "Deseja mesmo excluir?");
            if (resposta == 0) {
                tusuario.setId_tipouser(Integer.parseInt(txtCons.getText()));
                TipousuarioDAO dao = new TipousuarioDAO();
                dao.deletar(tusuario);
                JOptionPane.showMessageDialog(null, "Registro removido com sucesso!");
                txtCons.setText("");
                
                chcCadGrupo.setSelected(false);
                chcCadHard.setSelected(false);
                chcCadLocal.setSelected(false);
                chcCadPatr.setSelected(false);
                chcCadSoft.setSelected(false);
                chcCadUser.setSelected(false);

                chcConsGrupo.setSelected(false);
                chcConsHard.setSelected(false);
                chcConsLocal.setSelected(false);
                chcConsPatr.setSelected(false);
                chcConsSoft.setSelected(false);
                chcConsUser.setSelected(false);

                chcEditGrupo.setSelected(false);
                chcEditHard.setSelected(false);
                chcEditLocal.setSelected(false);
                chcEditPatr.setSelected(false);
                chcEditSoft.setSelected(false);
                chcEditUser.setSelected(false);

                chcAbrirOS.setSelected(false);
                chcFecharOS.setSelected(false);
                chcEditOS.setSelected(false);
                chcRelatOS.setSelected(false);
                
                chcCadGrupo.setEnabled(false);
                chcCadHard.setEnabled(false);
                chcCadLocal.setEnabled(false);
                chcCadPatr.setEnabled(false);
                chcCadSoft.setEnabled(false);
                chcCadUser.setEnabled(false);
                chcConsGrupo.setEnabled(false);
                chcConsHard.setEnabled(false);
                chcConsLocal.setEnabled(false);
                chcConsPatr.setEnabled(false);
                chcConsSoft.setEnabled(false);
                chcConsUser.setEnabled(false);
                chcEditGrupo.setEnabled(false);
                chcEditHard.setEnabled(false);
                chcEditLocal.setEnabled(false);
                chcEditPatr.setEnabled(false);
                chcEditSoft.setEnabled(false);
                chcEditUser.setEnabled(false);
                chcAbrirOS.setEnabled(false);
                chcFecharOS.setEnabled(false);
                chcEditOS.setEnabled(false);
                chcRelatOS.setEnabled(false);
                chcTodas.setEnabled(false);
                txtNomeGrupo.setEnabled(false);
                txtNomeGrupo.setText("");
                
                tblAncestorAdded(null);
                txtCons.requestFocus();
            }
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void txtConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsActionPerformed
        btnConsActionPerformed(null);
    }//GEN-LAST:event_txtConsActionPerformed

    private void txtNomeGrupoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeGrupoKeyTyped
        String caracteres="!@#$%¨&*()/\\*-+.,{}[]<>;:?°ºª'|\"=_`^~´¬§¢£³²¹°ºª";
        if(caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_txtNomeGrupoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlt;
    private javax.swing.JButton btnCanc;
    private javax.swing.JButton btnConAlt;
    private javax.swing.JButton btnCons;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JCheckBox chcAbrirOS;
    private javax.swing.JCheckBox chcCadGrupo;
    private javax.swing.JCheckBox chcCadHard;
    private javax.swing.JCheckBox chcCadLocal;
    private javax.swing.JCheckBox chcCadPatr;
    private javax.swing.JCheckBox chcCadSoft;
    private javax.swing.JCheckBox chcCadUser;
    private javax.swing.JCheckBox chcConsGrupo;
    private javax.swing.JCheckBox chcConsHard;
    private javax.swing.JCheckBox chcConsLocal;
    private javax.swing.JCheckBox chcConsPatr;
    private javax.swing.JCheckBox chcConsSoft;
    private javax.swing.JCheckBox chcConsUser;
    private javax.swing.JCheckBox chcEditGrupo;
    private javax.swing.JCheckBox chcEditHard;
    private javax.swing.JCheckBox chcEditLocal;
    private javax.swing.JCheckBox chcEditOS;
    private javax.swing.JCheckBox chcEditPatr;
    private javax.swing.JCheckBox chcEditSoft;
    private javax.swing.JCheckBox chcEditUser;
    private javax.swing.JCheckBox chcFecharOS;
    private javax.swing.JCheckBox chcRelatOS;
    private javax.swing.JCheckBox chcTodas;
    private javax.swing.JComboBox cmbMetod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtCons;
    private javax.swing.JTextField txtNomeGrupo;
    // End of variables declaration//GEN-END:variables
}
