/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.technobsoftwares.gpiec.formulario;

import br.com.technobsoftwares.gpiec.dao.Ordem_de_ServicoDAO;
import br.com.technobsoftwares.gpiec.dao.UsuarioDAO;
import br.com.technobsoftwares.gpiec.modelo.Ordem_de_Servico;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class FrmInConsOS extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form FrmInRelatOS
     */
    public FrmInConsOS() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtCons = new javax.swing.JTextField();
        btnCons = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbMetodo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaDesc = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtServiço = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaDesc1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtJustif = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtLocal = new javax.swing.JTextField();
        txtComp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fmtDataAbert = new javax.swing.JFormattedTextField();
        fmtDataFecha = new javax.swing.JFormattedTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        btnCanc = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Painel.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordens de Serviço"));
        Painel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Método de Pesquisa:");
        Painel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, -1, -1));

        txtCons.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsActionPerformed(evt);
            }
        });
        txtCons.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConsCaracteresConsulta(evt);
            }
        });
        Painel.add(txtCons, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 40, 30));

        btnCons.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCons.setText("Consultar");
        btnCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsActionPerformed(evt);
            }
        });
        Painel.add(btnCons, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Insira o código:");
        Painel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        cmbMetodo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbMetodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código", "Serviço", "Titulo", "Local", "Computador", "Equipamento", "Data de Abertura", "Data de Fechamento" }));
        Painel.add(cmbMetodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 132, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Serviço:");
        Painel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        txtaDesc.setColumns(20);
        txtaDesc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtaDesc.setLineWrap(true);
        txtaDesc.setRows(5);
        txtaDesc.setWrapStyleWord(true);
        txtaDesc.setEnabled(false);
        jScrollPane1.setViewportView(txtaDesc);

        Painel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 300, 100));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Descrição:");
        Painel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, 20));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Titulo:");
        Painel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        txtServiço.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtServiço.setEnabled(false);
        Painel.add(txtServiço, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 180, 30));

        txtaDesc1.setColumns(20);
        txtaDesc1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtaDesc1.setLineWrap(true);
        txtaDesc1.setRows(5);
        txtaDesc1.setWrapStyleWord(true);
        txtaDesc1.setEnabled(false);
        jScrollPane2.setViewportView(txtaDesc1);

        Painel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 300, 100));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Comentários de Fechamento:");
        Painel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, -1));

        txtJustif.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtJustif.setEnabled(false);
        Painel.add(txtJustif, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 180, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Data de Fechamento:");
        Painel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Computador:");
        Painel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, -1, -1));

        txtLocal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtLocal.setEnabled(false);
        Painel.add(txtLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 150, 30));

        txtComp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtComp.setEnabled(false);
        Painel.add(txtComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 150, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Local:");
        Painel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Data de Abertura:");
        Painel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 310, -1, -1));

        try {
            fmtDataAbert.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fmtDataAbert.setEnabled(false);
        fmtDataAbert.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Painel.add(fmtDataAbert, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, 150, 30));

        try {
            fmtDataFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fmtDataFecha.setEnabled(false);
        fmtDataFecha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Painel.add(fmtDataFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, 150, 30));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Serviço", "Titulo", "Status", "Local", "Computador", "Data de Abertura", "Descrição", "Data de Fechamento", "Comentário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        tbl.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.setViewportView(tbl);

        Painel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 1240, 200));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Status:");
        Painel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, -1, -1));

        txtStatus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtStatus.setEnabled(false);
        Painel.add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, 150, 30));

        btnCanc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCanc.setText("Sair");
        btnCanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancActionPerformed(evt);
            }
        });
        Painel.add(btnCanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 470, -1, 30));

        getContentPane().add(Painel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1260, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsActionPerformed
        btnConsActionPerformed(null);
    }//GEN-LAST:event_txtConsActionPerformed

    private void txtConsCaracteresConsulta(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsCaracteresConsulta
        String cons = txtCons.getText();

        if (cmbMetodo.getSelectedItem() == "Código") {
            //método para contar
            int quantCaracteres = cons.length();
            if (quantCaracteres > 2){
                cons = cons.substring (0, cons.length() - 1);
                txtCons.setText(cons);
            }
            //método apenas numeros
            String caracteres="0123456789";
            if(!caracteres.contains(evt.getKeyChar()+"")){
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtConsCaracteresConsulta

    private void btnConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsActionPerformed
        try {
            fmtDataFecha.setText("");
            Ordem_de_Servico os = new Ordem_de_Servico();
            Ordem_de_ServicoDAO dao = new Ordem_de_ServicoDAO();
            os.setId_ordem_servico(Integer.parseInt(txtCons.getText()));
            dao.pesquisar(os);

            txtServiço.setText(os.getFk_tipo_problema());
            txtJustif.setText(os.getTitulo_os());
            txtaDesc.setText(os.getDetalhes_os());
            txtComp.setText(os.getFk_pc());
            txtStatus.setText(os.getFk_status());
            fmtDataAbert.setText(os.getData_entrada());
            fmtDataFecha.setText(os.getData_fechamento());
            txtLocal.setText(os.getLocal_os());
            txtaDesc1.setText(os.getComentarios_fechamento());

            if (txtServiço.getText().equals("")) {
                txtCons.setText("");
                JOptionPane.showMessageDialog(null, "Ordem de Serviço não registrada!");
                txtCons.requestFocus();
            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Insira um ID válido!");
            txtCons.requestFocus();
        }
    }//GEN-LAST:event_btnConsActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        if (evt.getClickCount() ==  1) {
            fmtDataFecha.setText("");
            Ordem_de_Servico os = new Ordem_de_Servico();
            txtCons.setText(tbl.getValueAt(tbl.getSelectedRow(), 0).toString());
            txtServiço.setText(tbl.getValueAt(tbl.getSelectedRow(), 1).toString());
            txtJustif.setText(tbl.getValueAt(tbl.getSelectedRow(), 2).toString());
            txtStatus.setText(tbl.getValueAt(tbl.getSelectedRow(), 3).toString());
            txtLocal.setText(tbl.getValueAt(tbl.getSelectedRow(), 4).toString());
            txtComp.setText(tbl.getValueAt(tbl.getSelectedRow(), 5).toString());
            fmtDataAbert.setText(tbl.getValueAt(tbl.getSelectedRow(), 6).toString());
            txtaDesc.setText(tbl.getValueAt(tbl.getSelectedRow(), 7).toString());
            fmtDataFecha.setText(tbl.getValueAt(tbl.getSelectedRow(), 8).toString());
            txtaDesc1.setText(tbl.getValueAt(tbl.getSelectedRow(), 9).toString());

            Ordem_de_ServicoDAO dao = new Ordem_de_ServicoDAO();
            os.setId_ordem_servico(Integer.parseInt(txtCons.getText()));
            dao.pesquisar(os);
        }
    }//GEN-LAST:event_tblMouseClicked

    private void tblAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblAncestorAdded
        Ordem_de_ServicoDAO dao = new Ordem_de_ServicoDAO();
        List<Ordem_de_Servico> oss = dao.getListaOs();
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        model.setNumRows(0);
        for (Ordem_de_Servico os : oss) {
            model.addRow(new Object[]{
                os.getId_ordem_servico(),
                os.getFk_tipo_problema(),
                os.getTitulo_os(),
                os.getFk_status(),
                os.getLocal_os(),
                os.getFk_pc(),
                os.getData_entrada(),
                os.getDetalhes_os(),
                os.getData_fechamento(),
                os.getComentarios_fechamento()
            });
        }
    }//GEN-LAST:event_tblAncestorAdded

    private void btnCancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel;
    private javax.swing.JButton btnCanc;
    private javax.swing.JButton btnCons;
    private javax.swing.JComboBox cmbMetodo;
    private javax.swing.JFormattedTextField fmtDataAbert;
    private javax.swing.JFormattedTextField fmtDataFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtComp;
    private javax.swing.JTextField txtCons;
    private javax.swing.JTextField txtJustif;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JTextField txtServiço;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextArea txtaDesc;
    private javax.swing.JTextArea txtaDesc1;
    // End of variables declaration//GEN-END:variables
}
