/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.technobsoftwares.gpiec.formulario;

import br.com.technobsoftwares.gpiec.Nseriegabinete;
import br.com.technobsoftwares.gpiec.dao.GabineteDAO;
import br.com.technobsoftwares.gpiec.dao.Local_2DAO;
import br.com.technobsoftwares.gpiec.modelo.Gabinete;
import br.com.technobsoftwares.gpiec.modelo.Local_2;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author lab
 */
public class FrmInCadGabinete extends javax.swing.JInternalFrame {
    /**
     * Creates new form FrmInCadHardware
     */
    public FrmInCadGabinete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMarcaHD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCapacidadeHD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbRpmHD = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFreq = new javax.swing.JTextField();
        txtMarcaMemo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTaman = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtNomePlac = new javax.swing.JTextField();
        txtDescPlac = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNomeProc = new javax.swing.JTextField();
        txtMarcaProc = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        btnCad = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        cmbLocalProc = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        cmbGabinProc = new javax.swing.JComboBox();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Hardware"));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de HD"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Marca:");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        txtMarcaHD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel5.add(txtMarcaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 130, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Capacidade:");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        txtCapacidadeHD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel5.add(txtCapacidadeHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 130, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("RPM:");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        cmbRpmHD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbRpmHD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "*RPM*", "5400", "7200", "10000", "15000", " " }));
        jPanel5.add(cmbRpmHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 130, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("HD", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Memória"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Marca:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Frequência:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        txtFreq.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel2.add(txtFreq, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 130, 30));

        txtMarcaMemo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel2.add(txtMarcaMemo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 130, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Tamanho:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        txtTaman.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel2.add(txtTaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 130, 30));

        jTabbedPane1.addTab("Memória", jPanel2);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Placas Adicionais"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNomePlac.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel4.add(txtNomePlac, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 130, 30));

        txtDescPlac.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel4.add(txtDescPlac, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 130, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Nome:");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Descrição:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jTabbedPane1.addTab("Placas Adicionais", jPanel4);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Processador"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Marca:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, 20));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Nome:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        txtNomeProc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel3.add(txtNomeProc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 130, 30));

        txtMarcaProc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel3.add(txtMarcaProc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 130, 30));

        jTabbedPane1.addTab("Processador", jPanel3);

        jPanel6.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 580, 270));

        btnLimpar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLimpar.setText("Limpar");
        jPanel6.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, 30));

        btnCad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCad.setText("Cadastrar");
        jPanel6.add(btnCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, 30));

        btnSair.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar(evt);
            }
        });
        jPanel6.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 100, 30));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Local:");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        cmbLocalProc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbLocalProc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "*LOCAL*" }));
        cmbLocalProc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbLocalProcItemStateChanged(evt);
            }
        });
        cmbLocalProc.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cmbLocalProcAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel6.add(cmbLocalProc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 180, 30));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Gabinete:");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        cmbGabinProc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbGabinProc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "*GABINETE*" }));
        cmbGabinProc.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cmbGabinProcAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel6.add(cmbGabinProc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 180, 30));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 620, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar
        this.dispose();
    }//GEN-LAST:event_Cancelar

    private void cmbLocalProcAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cmbLocalProcAncestorAdded
        Local_2DAO dao = new Local_2DAO();
        List<Local_2> locais = dao.getLista();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cmbLocalProc.getModel();
        for (Local_2 local : locais) {
            model.addElement(local.getNome_local());
        }
    }//GEN-LAST:event_cmbLocalProcAncestorAdded

    private void cmbGabinProcAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cmbGabinProcAncestorAdded
        GabineteDAO dao = new GabineteDAO();
        Nseriegabinete nseriegabinete = new Nseriegabinete();

        List<Gabinete> gabinetes = dao.getLista();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cmbGabinProc.getModel();
        for (Gabinete gabinete : gabinetes) {
            model.addElement(nseriegabinete.getNseriefabricante());
        }
    }//GEN-LAST:event_cmbGabinProcAncestorAdded

    private void cmbLocalProcItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbLocalProcItemStateChanged
        if (cmbLocalProc.getSelectedIndex()!= 0) {
            //cmbComp.removeAllItems();
            //nome_local = String.valueOf(cmbLocal.getSelectedItem());           
            //local.setId_local(cmbLocal.getSelectedIndex());
            //os = cmbLocal.getSelectedIndex();
            cmbGabinProc.setEnabled(true);
            cmbGabinProcAncestorAdded(null);
        }else{
            cmbGabinProc.removeAllItems();
            cmbGabinProc.setEnabled(false);            
        }
    }//GEN-LAST:event_cmbLocalProcItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCad;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox cmbGabinProc;
    private javax.swing.JComboBox cmbLocalProc;
    private javax.swing.JComboBox cmbRpmHD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtCapacidadeHD;
    private javax.swing.JTextField txtDescPlac;
    private javax.swing.JTextField txtFreq;
    private javax.swing.JTextField txtMarcaHD;
    private javax.swing.JTextField txtMarcaMemo;
    private javax.swing.JTextField txtMarcaProc;
    private javax.swing.JTextField txtNomePlac;
    private javax.swing.JTextField txtNomeProc;
    private javax.swing.JTextField txtTaman;
    // End of variables declaration//GEN-END:variables
}
